### ISSUE TITLE
Crash on LimitStencilTableFactory::Create

### ISSUE THREAD

**Issue by OlivierRenouardMaverickRender** [PixarAnimationStudios/OpenSubdiv#1006]
Attempting to create a limit stencil table with a face varying  StencilTable as cvStencils argument will crash if there are face varying seams in the stencil table (ie uv seams).

**Comment by barfowl** [comment]
From what I can see, the LimitStencilTableFactory does not support the creation of face-varying stencils at all.  Unlike StencilTableFactory, there is no "interpolationMode" Option to indicate that the given StencilTable is for face-varying data (a StencilTable instance does not retain that context) or that the limit points should be for a face-varying channel in its absence.  The Create() method also does not attempt to evaluate face-varying or varying limit points in any way.

So we will have to add more to the LimitStencilTableFactory::Options interface and complete the missing functionality internally to get this working.  There is a new release planned for the coming weeks, and we should be able to include this with it.

Thanks for bringing it to our attention.

**Comment by OlivierRenouardMaverickRender** [comment]
Ok thanks. I assumed it would use the interpolation of the StencilTable passed as argument, but if not explains the issue.

**Comment by barfowl** [comment]
I wanted to re-open this briefly as it does raise an issue that needs addressing, and I do have a solution being tested now.  We should have this merged into dev within the next week so it hopefully won't be open again for long.  Someone else had wondered if closing this issue meant we were not going to address it, which is not the case.  Thanks

**Comment by barfowl** [comment]
A solution to this issue has now been merged into the dev branch with #1012 and will be included in the next release.
