### ISSUE TITLE
Compilation Issue with v3.3.3 using latest VS2017 (v15.9.2)

### ISSUE THREAD

**Issue by adam-hartshorne** [PixarAnimationStudios/OpenSubdiv#1029]
When attempting to compile with the last Release version of OpenSubDiv (v3,3,3) with the latest version of vs2017, I get the following error,

```
3>...opensubdiv\far\topologyrefinerfactory.h(54): fatal error C1001: An internal error has occurred in the compiler.
3>(compiler file 'msc1.cpp', line 1518)
3> To work around this problem, try simplifying or changing the program near the locations listed above.
3>Please choose the Technical Support command on the Visual C++
3> Help menu, or open the Technical Support help file for more information (compiling source file cudaEvalOuput.cpp)
3>INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe'
3>    Please choose the Technical Support command on the Visual C++
3>    Help menu, or open the Technical Support help file for more information
3>cl : Command line error D8040: error creating or communicating with child process
3>Done building project "subdivEvaluation.vcxproj" -- FAILED.
```

Switching to LLVM / Clang, the same project compiles fine (and used to on an older version of VS2017).

**Comment by davidgyu** [comment]
Interesting. I haven't been able to reproduce this using either v15.9.2 or v15.9.3 of VS2017 with the v3_3_3 tagged source of OpenSubdiv (Windows 10 1809 in case that matters).

You mentioned "Release". Are you hitting this internal error only with optimized Release builds or are you also seeing this with Debug builds? Have you been able to try out v15.9.3 to see if this problem has been recently fixed?

Can you share any more about the build environment of your subdivEvaluation.vcxproj?

Thanks!
-David

**Comment by jtran56** [comment]
Filed as internal issue #OSD-248.

**Comment by davidgyu** [comment]
Marking this closed. This is working correctly in our testing with VS2015 through VS2022.
Please reopen or file a new ticket with additional information if this is still a problem for you.
