### ISSUE TITLE
Lack of Partial 2nd Order Derivatives for Uniform Subdivision

### ISSUE THREAD

**Issue by oracle3001** [PixarAnimationStudios/OpenSubdiv#1030]
I appears that 2nd order derivatives aren't calculated for uniform subdivision schemes. 

Is that a feature or a bug? Would it be possible to add support for them?

**Comment by barfowl** [comment]
Derivatives at arbitrary locations need to be evaluated with a PatchTable, and for historical reasons, the PatchTable constructed from uniform subdivision is just the piecewise linear collection of subdivided faces.  So evaluating 2nd derivatives for the resulting bilinear faces produces values of 0 (and remember that 1st derivatives reflect the face and not the underlying surface).  This linearly approximating PatchTable was more intended for display than evaluation.

We could allow construction of a PatchTable from uniform subdivision with bicubic patches, but its cost and size can quickly become excessive for higher subdivision levels, while offering no evaluation advantages over one from adaptive refinement (often less, as adaptive better captures sharper creases with locally greater depth).

If we were to allow creation of a non-linear uniform PatchTable (and we have been considering it for a while), it would need to come with a new option that would need to be explicit.  We also have to account for all existing code that deals with potentially linear uniform PatchTables (e.g. the LimitStencilTableFactory) and potentially propagate that option in some usage.

At this point its relatively easy for us to generate the table itself, but more effort to track down and deal with those dependencies.  And given its limited use and high potential for abuse, we're wondering if that effort is worth it.

**Comment by barfowl** [comment]
Given lack of any further questions on this issue, I'm going to close it.  To summarize, uniform subdivision provides a linear approximation to the limit surface and 2nd derivatives of that linear approximation evaluate to zero.  There are no current plans to generate non-linear patches for uniform subdivision.
