### ISSUE TITLE
Random incorrect or correct X,Y,Z positions

### ISSUE THREAD

**Issue by thegendolz** [PixarAnimationStudios/OpenSubdiv#1059]
I have a huge problem with my X,Y,Z positions using the HBR class of the opensubdiv library. What happens is that the subdivision done using opensubdiv sometimes returns random numbers or memory adresses for the positions (x, y, z) and sometimes the correct positions. What basically happens is that either my subdivision works correctly and I am able to display a subdivided mesh using opensubdiv or my mesh is a random (x, y, z) position which results in a weird mesh. My problem is that it is completely random (50/50) whether my subdivision works or not.

I have looked at wrong memory positions, wrong vertices and wrong faces and they all seem fine before I call the refine function however after the refine function is done the problems occur. Often only 1 of the x,y,z positions are wrong, so my x,z positions can be correct but my y is a complete random high number. I was wondering if anybody knows how this problem can occur, did I do something wrong?

This is my initilization where I put my own vertex positions and faces into the opensubdiv objects:
   
```
catmark = new OpenSubdiv::HbrCatmarkSubdivision<Vertex>();
    hmesh = new OpenSubdiv::HbrMesh<Vertex>(catmark);
    int nverts = vertexCoords.size();
    int nfaces = faceValences.size();

    Vertex v;
    for (int i=0; i<nverts; ++i) {
        v.SetPosition(vertexCoords.at(i).x(), vertexCoords.at(i).y(), vertexCoords.at(i).z());
        hmesh->NewVertex(i, v);
    }

    int *test = new int[faceCoordInd.size()];
    //std::vector<int> facevertx(faceCoordInd.size());
    for(int i=0; i < faceCoordInd.size(); i++){
        test[i] = faceCoordInd.at(i);
    }

    int * fv = test;
    for (int i=0; i<nfaces; ++i) {
        int nv = faceValences.at(i);

        hmesh->NewFace(nv, fv, 0);

        fv+=nv;
    }
    hmesh->SetInterpolateBoundaryMethod(OpenSubdiv::HbrMesh<Vertex>::k_InterpolateBoundaryEdgeOnly);
    // Call 'Finish' to finalize the data structures before using the mesh.
    hmesh->Finish();
```

Then I subdivide using the following code:

```
OpenSubdiv::HbrMesh<Vertex>* subdivideOpenSubdiv(int subdivisionSteps, OpenSubdiv::HbrMesh<Vertex>* hmesh, int startFace, int startVertex){
    qDebug() << "================[Subdivision]=================";
    qDebug() << "Before:: " << hmesh->GetNumFaces() << " :: "<< hmesh->GetNumVertices();



    int maxlevel=subdivisionSteps,
    firstface=startFace,
    firstvertex=startVertex;
    for (int level=0; level<maxlevel; ++level) {
        qDebug() << "TEST";
        int nfaces = hmesh->GetNumFaces();
        if (level==(maxlevel-1)) {
            firstvertex = hmesh->GetNumVertices();
        }

            for (int face=firstface; face<nfaces; ++face) {
                OpenSubdiv::HbrFace<Vertex> * f = hmesh->GetFace(face);

                f->Refine();


             }

            firstface = nfaces;
        }


    return hmesh;
}
```

This is how I get my vertex positions, on line 3 of this code I get my Vertex positions which are sometimes incorrect:

```
for (int vert = (startVerts.at(subdivlevel)); vert < (startVerts.at(subdivlevel+1)); vert++) {
        const float * pos = hmesh->GetVertex(vert)->GetData().GetPosition();
        QVector3D vertexPos = QVector3D(pos[0], pos[1], pos[2]);
        vertexCoords.append(vertexPos);
        vertexNormals.append(vertexPos.normalized());
    }
```

Below shows the images of my subdivision. As visible the first one is the correct subdivision however the 2nd one is not. My x postions go to an infinite random number while my y,z positions are correct.
[See images here](https://imgur.com/a/OHHYlOY)

**Comment by anil100391** [comment]
How does your vertex data structure look?

**Comment by thegendolz** [comment]
I've solved the issue, there were problems with my pointers who were allocated to missing data

**Comment by barfowl** [comment]
Glad to hear you found the problem.

I was curious as to why you are using Hbr though as its usage has been discouraged for several years now since 3.0.  The overview in the [documentation for Hbr](http://graphics.pixar.com/opensubdiv/docs/hbr_overview.html) tries to make this clear, including:

> If your code is currently depending on Hbr functionality, we recommend migrating to the newer APIs as we cannot guarantee that this code will be maintained in future releases.

If you don't have a specific reason for continuing to use Hbr despite its status, I'm wondering what more we might need to do to discourage new users from accidentally making use of it.  Thanks

**Comment by thomthom** [comment]
@barfowl To avoid accidental use of deprecated API you could add a compiler warning/error which the API users have to explicitly mute with a macro definition. Similar strategy that was done for the toolset in VS2017 (https://github.com/google/googletest/issues/1111)

**Comment by barfowl** [comment]
Yes @thomthom, thanks, we plan to at some point, but it is not yet "officially deprecated" -- probably next major version.  In the meantime (and even then) we'd like to steer new users away from this before they've written the code that will issue the deprecation warnings.
