### ISSUE TITLE
Automatic generation of creases?

### ISSUE THREAD

**Issue by FrankEscobar** [PixarAnimationStudios/OpenSubdiv#1063]
I need to create creases depending on the normals, something similar to 3dsmax smoothing groups, is there something like that in OpenSubDiv or should I code it myself from scratch and send that edges to OSD as crease edges?

Thank you in advance

**Comment by barfowl** [comment]
OpenSubdiv does not have the concept of "smoothing groups".  The base mesh of a subdivision surface defines a surface that is smooth everywhere by default.  The creasing features exist to allow the introduction of sharp or semi-sharp features to deviate from the default smooth shape where desired.

So, yes, you will need to explicitly sharpen the edges between faces in different smoothing groups, or where face normals deviate beyond some threshold, etc.

**Comment by jtran56** [comment]
Filed as internal issue #OSD-259.
