### ISSUE TITLE
Do not link with tbbmalloc_proxy on Linux?

### ISSUE THREAD

**Issue by tdelame** [PixarAnimationStudios/OpenSubdiv#1064]
As far as I understood [1](https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Linux_C_Dynamic_Memory_Interface_Replacement.html) [2](https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/297307),  `libtbbmalloc_proxy.so` is used on Linux to replace so glibc functions. To do so, one must load such library before any other shared module, by using `LD_PRELOAD`. 

I had a crash in glibc's `free` function when `tbbmalloc_proxy` was a shared module loaded by an application but not pre-loaded. The crash immediately disappeared when I removed `tbbmalloc_proxy` from the loaded modules or when I pre-loaded it.

Currently, `FindTBB.cmake` adds `tbbmalloc_proxy` and `tbbmalloc_proxy_debug` into `TBB_LIBRARIES`. Should it be fixed?

**Comment by jtran56** [comment]
Filed as internal issue #OSD-258.

**Comment by davidgyu** [comment]
This should be fixed now. Thanks for reporting!
