### ISSUE TITLE
Usage of Feature Adaptive Subdivision in OpenSubdiv

### ISSUE THREAD

**Issue by VadiMysore** [PixarAnimationStudios/OpenSubdiv#1079]
Hi there!
I am trying to create a solid/surface by stitching together the limiting bi-cubic b-spline surfaces resulting from the feature adaptive subdivision of the initial control cage. None of the examples supplied with the released versions of OpenSubdiv satisfy my requirements. Below is the snippet of code am using to generate the limiting bicubis bsplines. The input is a simple cube. 

refiner = Far::TopologyRefinerFactory<Descriptor>::Create(desc,
															  Far::TopologyRefinerFactory<Descriptor>::Options(type, options));

Far::TopologyRefiner::AdaptiveOptions options(subdivisionLevel);
		options.useSingleCreasePatch = false;

refiner->RefineAdaptive(options);

// Generate a set of Far::PatchTable that we will use to evaluate the
// limiting surface
Far::PatchTableFactory::Options patchOptions;
		patchOptions.endCapType = Far::PatchTableFactory::Options::ENDCAP_BSPLINE_BASIS;

Far::PatchTable const* patchTable = Far::PatchTableFactory::Create(*refiner, patchOptions);

// Compute the total number of points we need to evaluate patchtable.
// we use local points around extraordinary features.
int nRefinerVertices = refiner->GetNumVerticesTotal();
int nLocalPoints = patchTable->GetNumLocalPoints();

// Create a buffer to hold the position of the refined verts and
// local points, then copy the coarse positions at the beginning.
subdivVertexVec.resize(nRefinerVertices + nLocalPoints);
allSUbdivVertices = &subdivVertexVec[0];

for (int i = 0; i < (int)meshInfo.m_facetVertices.size(); ++i)
{
	allSUbdivVertices[i].SetPosition(meshInfo.m_facetVertices[i][0], 
                                  meshInfo.m_facetVertices[i][1], meshInfo.m_facetVertices[i][2]);
}
// Adaptive refinement may result in fewer levels than maxIsolation.
int nRefinedLevels = refiner->GetNumLevels();

Far::PrimvarRefiner primvarRefiner(*refiner);

SESubdivVertex* sourceVertices = allSUbdivVertices;
for (int level = 1; level < nRefinedLevels; ++level)
{
			SESubdivVertex* destinationVertices = NULL;
			int numLevelVertices = 0;

			numLevelVertices = refiner->GetLevel(level - 1).GetNumVertices();

			destinationVertices = sourceVertices + numLevelVertices;

			primvarRefiner.Interpolate(level, sourceVertices, destinationVertices);

			sourceVertices = destinationVertices;
}

// Evaluate local points from interpolated vertex primvars.
patchTable->ComputeLocalPointValues(allSUbdivVertices, &allSUbdivVertices[nRefinerVertices]);

int numPatchArrays = patchTable->GetNumPatchArrays();

for (int array = 0; array < numPatchArrays; array++)
{
		Far::PatchDescriptor patchDescriptor = patchTable->GetPatchArrayDescriptor(array);

		if (patchDescriptor == Far::PatchDescriptor::REGULAR)
		{
			int numPatches = patchTable->GetNumPatches(array);

			for (int patch = 0; patch < numPatches; patch++)
			{
					Far::ConstIndexArray controlVertexIndices;
					SESubdivVertexVector patchControlVertices;

					controlVertexIndices = patchTable->GetPatchVertices(array, patch);

					for (int cv = 0; cv < controlVertexIndices.size(); cv++)
					{
						int index = controlVertexIndices[cv];
						patchControlVertices.push_back(allSUbdivVertices[index]);
					}

					patchCVsVector.push_back(patchControlVertices);
			}

			for (int i = 0; i < (int)patchCVsVector.size(); i++)
			{
					DoubleVector patchControlVertexCoords;
					PK_BSURF_t patchSurf = PK_ENTITY_null;
					PK_UVBOX_t surfUVBox = { 0 };
					PK_BODY_t sheetBody = PK_ENTITY_null;

					for (int cv = 0; cv < patchCVsVector[i].size(); cv++)
					{
						const double* cvCoords = NULL;

						cvCoords = patchCVsVector[i][cv].GetPosition();

						patchControlVertexCoords.push_back(cvCoords[0]);
						patchControlVertexCoords.push_back(cvCoords[1]);
						patchControlVertexCoords.push_back(cvCoords[2]);
					}

					//Fit b-splines from the control vertices obtained above for each patch.
				}
			}
		}

The patches generated appear strange at one corner. They seem to all have one corner "folded up" as shown in the attached image.

![bicubic_patch](https://user-images.githubusercontent.com/24560022/54510205-67be1a80-491a-11e9-8d65-cc15ae430adf.JPG)

Can you please verify whether what I am trying to achieve is feasible in OpenSubdiv with adaptive subdivision?

Thanks,
Vadi Mysore

**Comment by barfowl** [comment]
What you are trying to achieve is feasible and has been done elsewhere (e.g. #968).  As noted, there is no "example" that fits your task, but much of your code here to build the PatchTable and interpolate the required control points is illustrated in one of the Far tutorials (tutorials/far/tutorial_6).  Only the traversal of the PatchTable to identify the control points per patch is absent.

The image you posted shows the result of some other library evaluating the patch, not the control points of the patch used in the evaluation.  I have exported the control points of the BSpline patches in the PatchTable for a cube and they do match my expectations (the wireframe I generated is a bit messy or I would post it here).  I haven't gone over your code here in detail, but the fact that "all" patches evaluate incorrectly makes me suspect some kind of off-by-one error.

I'll have a closer look when I have a bit more time.

In the meantime, if you are trying to capture the BSpline patches that OpenSubdiv generates and use them in some other context, then you do need to be more aware of some of the details.  In particular, OpenSubdiv's representation and evaluation of patches on boundaries are coordinated to avoid explicitly extrapolating additional control points, so you will need to explicitly extrapolate them yourself if you want to use a standard 16-point uniform bicubic B-spline evaluation function.  More details on that can be found in the documentation on patch parameterization [here](https://github.com/PixarAnimationStudios/OpenSubdiv/blob/master/documentation/far_overview.rst#patch-parameterization).

This won't be a problem for the cube example here, or any other "solid" model that does not have boundaries, but it does need to be addressed if you are trying to export a patch representation of more general models.

**Comment by VadiMysore** [comment]
H there!
Thanks for the quick and detailed response. I appreciate it.

As you see in my code to extract the control vertices of the resulting patches, I am just indexing into a global list of vertices that I maintain using the control vertex indices for a patch gotten from OpenSubdiv API. I do use another library to actually create a bicubic b-spline surface from these control vertices. It is a very straightforward interface. I just want to be sure that these control vertices are correct and the way am extracting them is correct as well.

There are several non-OpenSubdiv solutions to surface subdivision in commercial CAD software products. NX does have one and it always produces a b-spline patch per original quad face of the initial control cage. This seems to be based on the algorithm detailed in the paper, "Patching Catmull-Clark Meshes", by J¨org Peters. This is the kind of solution I am looking for. In fact, if OpenSubdiv can provide this solution, it will be extremely useful in CAD software products wherein users often expect a lighter, classic b-rep model in lieu of a heavy triangulated mesh model. Is it something that OpenSubdiv will look into on a priority basis? I did refer to case #968 before penning down my issue. It made me aware of the current limitations of OpenSubdiv as far as adaptive subdivision goes.

Also, going by your comments n the penultimate paragraph, if I extract the patch control vertices the way I am doing now, is there no guarantee that they will all be edge continuous? I mean, if I generate each patch separately and then try to stitch them together to generate a composite surface or solid, there is no guarantee that they will be contiguous to each other at their boundaries? I thought that OpenSubdiv returned the control vertices for all the resulting limiting surface patches and they together represented the initial control cage. Aren't the "Local Points" the additional  control points to account for the extraordinary points? I will have to reread the section you have pointed to. 

By the way, our control cages will always be a manifold solid/surface comprising only quad faces.

I highly appreciate your time and if you could spot any errors in the way am extracting the control vertices that results in the weird folded patch, it will be very helpful.

Thanks!

**Comment by jilliene** [comment]
Filed as internal issue #OSD-280

**Comment by VadiMysore** [comment]
@jilliene - what this internal issue #OSD-280 will address?

Thanks!

**Comment by c64kernal** [comment]
@VadiMysore — apologies for any confusion, that’s just a bookkeeping number for us so that we can track all the issues on GitHub in an internal tool — it’s just for our own bookkeeping, please ignore!

**Comment by VadiMysore** [comment]
@jilliene - thanks for clearing the confusion. Is it possible to expect a solution to the issue I have detailed above so that CAD software products can benefit from it? Currently the feature adaptive subdivision in OpenSubdiv is more geared towards direct rendering of subdivision results where as CAD software products expect creating solid/surface from the resulting bicubic b-spline surface patches.

**Comment by barfowl** [comment]
@VadiMysore  it is unclear at this point what -- if any -- action is warranted on this issue.

The Far::PatchTable in OpenSubdiv provides a complete piecewise parameteric representation of the limit surface -- not just for direct rendering but for arbitrary evaluation, differential analysis, etc. There is nothing that inhibits the parametric patches in the PatchTable from being exported and evaluated elsewhere (though a deeper understanding of the details of the patch representation is warranted).

There is clearly a problem with the code provided that I regret I have not had the time to investigate further.  The contents of the PatchTable, i.e. the individual bicubic B-spline patches, for this example do appear to be correct as the following uniform tessellation of each patch illustrates:

![cc_cube_bspline](https://user-images.githubusercontent.com/4130807/54770231-0b7c2480-4bc0-11e9-935b-74fe9640589c.jpg)

This was created from a tool of mine (that I cannot share) that builds the PatchTable similar to the way it is created in tutorials/far/tutorial_6 and then exports the control hulls of the patches or a uniform tessellation of them.  Unfortunately the overlapping nature of adjacent uniform bicubic B-spline patches makes the output of the hulls mess, but the tessellated patches here do match expectations.

For the code provided above, I suggest verifying that the control points being passed to the external evaluation function match what you expect for a patch on what amounts to a crude sphere -- it looks like a corner point of the patch is incorrect.  Whether that point is from an adjacent patch in the array or interpolated incorrectly is difficult to determine without seeing or knowing more, but that may provide some insight into where the problem lies.

I will have a closer look at the code myself when I have more time, but I currently have more pressing priorities.

**Comment by VadiMysore** [comment]
@barfowl - Hi Barry! Thanks indeed for your time. I appreciate your taking time off to respond to my messages. 

Based on your previous response, I have the following questions/requests.

1. The Far::PatchTable may have the complete piecewise parameteric representation of the limit surface
but the interface is not good enough for one to use it directly. For example, as you have experienced yourself, why should I as a consumer of the APIs be concerned about the overlapping nature of the adjacent uniform bi-cubic patches? All that I want from the OpenSubdiv for the feature adaptive subdivision, are the final limiting bicubic surface patches that together represent the final result. If you can extract the correct final result through tessellation of these patches, then I should be able to get the limiting surface patches that stitch together to form a solid/surface without a deeper understanding of the patch representation. I think that is what OpenSubdiv lacks currently with respect to Adaptive refinement. It is much clearer for uniform refinement and I have been using the latter successfully.

2. The third party software library I am using to create bicubic patches expects the control vertices in the following format, "The vertices are so arranged that they vary most quickly with v and then with u."  So, when I get the control vertices out of the PatchTable for each patch, what is the order of these control vertices? Do you think that this could be the source of the problem I am seeing?

3. Also, OpenSubdiv produces far too many patches. If they are all G2 continuous, this should not matter. But in CAD applications, we want ideally one limiting bicubic surface patch per quad face of the initial control cage. CAD applications like NX ensure this in their surface subdivision. Is it possible with OpenSubdiv? If not, can it be enhanced?

Please take your time in responding to my queries. I respect your time and it has been a pleasure to interact with you.

Thanks!

**Comment by barfowl** [comment]
Granted the Far::PatchTable is less than ideal, but something I mentioned seems to have been misinterpreted...

1. The bicubic patches do not "overlap".  The overlapping I mentioned was in reference to the control hulls of the patches (remember these are all uniform B-spline patches, not non-uniform with clamped end knots).  The PatchTable only includes the collection of patches that stitch together to form the limit surface.  These can be evaluated relative to the base face within OpenSubdiv without knowledge of their organization.

2. Based on the image you provided it does not look to me like the ordering of the control vertices is your problem (sounds like the expected ordering is the same -- the OpenSubdiv ordering is illustrated in the documentation on patch parameterization previously noted).  It looks to me like at least one of the control vertices at the corner is clearly wrong relative to the others.  I recommend verifying that each set of 16 bicubic Bspline points is reasonable before inspecting the results of the evaluation.  And make sure that the bicubic patch evaluator you are using is for a UNIFORM bicubic BSpline, i.e. it does not assume a single knot interval with clamped ends by default if it is a more general BSpline patch evaluator.  Displaying the control vertices of the patch in the same view as the resulting tessellation should provide some insight.

3. OpenSubdiv produces varying numbers of patches to vary the accuracy relative to the true Catmull-Clark limit surface.  Where extra-ordinary vertices or creases are present, more patches are generated to improve the accuracy whereas using too few compromises accuracy -- the level of adaptive refinement is one way to affect that accuracy.  For historical reasons, a minimum of one level is required, so, yes, more patches will be generated than the minimal one-per-quad.  Work is in progress to improve that situation, but will not be released any time soon (though it may be unofficially supported in common cases).  Unlike CAD applications, OpenSubdiv must often deal with non-quad faces, which creates additional complications in this case.

**Comment by VadiMysore** [comment]
@barfowl - Hi Barry!
Finally good news! I was able to successfully create bicubic b-spline patch surfaces and stitch them all together to form a composite surface/solid. You were correct in your observation that I was using "open uniform knot vector", which clamped the surface ends with the corner control vertices. Using the truly uniform knot vector got me the correct patch. Thanks for the help!

I now have a few more questions and need your advice on them.

1. Since the number of patches generated is proportional to the number of levels of refinement, you seem to suggest using a minimum of one level. For some of the simple models I tested, I did not find much of a difference in the "quality" of the output surfaces  with increasing levels (> 1). What is the optimal level then to use before diminishing returns kick in? 

2. Since we will be subdividing in a dynamic context, wherein every drag step of the initial control cage's quad faces will generate the limiting patches for a given level, constructing b-spline surfaces and stitching them together during every drag step can be expensive. Will using stencils and dynamically evaluating the patch parameters, as some of the OpenSubdiv examples do, help in speeding up the drag experience?

3. I also seem to have some issues with assigning weights to edges to keep them sharp. It did not seem to work in my previous attempts at prototyping it. If I see the same issues again with it, I would like to get an opinion from you on what I am doing.

Thank you very much again for all your help!

**Comment by barfowl** [comment]
Glad to hear you made some progress @VadiMysore 

As for your latest questions...

1. A minimum of one level of adaptive level of refinement is a historical requirement.  You can get away with 0 if your mesh is suitably conditioned, but this code is not robust and will crash if your mesh has certain features, so I cannot officially recommend it.  As for an "optimal" maximum level, that question is not easily answered without knowing the kinds of features your meshes contain and how you plan to use the results.  Obviously close inspection or compatibility with some other tool that may be generating a higher degree of accuracy puts greater demands on the accuracy you need to retain. If you use the creasing, you need to choose a level deep enough to capture the shape of those creases.  If you're tessellation rates are low, the value of additional levels and accuracy is diminished.
The example viewers allow you to modify some of these variables and inspect their effects.

2. Yes, the StencilTables and PatchTables are designed to support dynamic changes to the control points of the mesh.  The PatchTables and StencilTables are created once the topology of the mesh is fixed, then changes to the control points of the mesh can be applied to update the control points of the patches -- not reconstructing the patches themselves.

3. If you want to use edge sharpness then you must set the adaptive refinement level accordingly to capture their shape (as noted also in 1) as the semi-sharp creasing relies on adaptive subdivision.  If you are making edges infinitely-sharp rather than semi-sharp, you will probably want to set the "useInfSharpPatch" options for the PatchTable construction and adaptive refinement to use a smaller number of truly sharp patches (historically this was not done by default and so now must be explicitly specified).

**Comment by VadiMysore** [comment]
@barfowl - Hi Barry!
Thanks as always for your time and very helpful suggestions.

1. I have not really explored sharp/Semi-sharp creases, weights for edges and other features of  OpenSubdiv. I have only explored the uniform, adaptive refinement modes and patch tables, thus far. As you suggest, we will have to decide the level needed for a particular input mesh topology and the other features mentioned above that a user wants in the final result. So you say that it will not be a good idea to expose the number of levels of refinement to the end user as they will have no idea of what it means? Should the software decide based on what you have suggested?

2. I only have used PatchTables thus far. But plan to use StencilTables to speed up the computations. You seem suggest using these two together in situations wherein the topology of the input mesh is fixed and only its control points may change, say, due to transformations? So if the topology of the mesh changes, we will need to rebuild the PatchTable and the StencilTable? 

Also, in case of fixed topology meshes, should we build the PatchTable and the StencilTable only once upfront and then keep using them to apply the changes to the mesh control points to get the updated patch control points? Is there a simpler example of the usage of PatchTable and StencilTables together?

3. I also observed that if the initial mesh comprising quads, is not a solid, then the results are different between uniform and adaptive refinements. The following picture depicts it.

![SubDEffects](https://user-images.githubusercontent.com/24560022/55212912-9613e380-51bf-11e9-8ffb-3ea858cfdf0d.jpg)

a) How can I fix the free edges here to remain sharp? By assigning infinite weights to them so that they do not "fray" like they do in this picture?
b)Why having level 1 for adaptive refinement gives the weird result you see ?

I looked for the "useInfSharpPatch" option for the patch table and could not find it. I am using Release 3.0.5 of OpenSubdiv. Obviously, this option is not available in this release. If I get the latest release and use this option, will this solve the problems I see with adaptive refinement in the case I have quoted? 

Also, in an unrelated case, I expected a (near) perfect torus for the case shown below. But I get the following results.

![SubDEffects 1](https://user-images.githubusercontent.com/24560022/55213367-17b84100-51c1-11e9-9c83-04726bf92d42.jpg)

Why there is some weirdness in the final result  with both refinement methods. The initial cage was derived by sweeping a square cross-section around an octagonal spine curve. 

Also, what is the effect of the various Sdc::Options::VtxBoundaryInterpolation options? They do not seem to have any impact on the final result no matter which one of the three: VTX_BOUNDARY_NONE, VTX_BOUNDARY_EDGE_ONLY, VTX_BOUNDARY_EDGE_AND_CORNER, I use. The documentation with a 2D example on the Pixar web site only adds to the confusion.

Thanks for your help.

**Comment by VadiMysore** [comment]
@barfowl - Hi Barry! Thanks for your time and valuable inputs. You have answered all my questions with a lot of patience. I highly appreciate it. 

As you suggest, I will play around with the examples provided to understand the effect of the various options to the subdiv algorithms.

You did mention about the boundary patches in one of your previous messages and I apologize that I missed it, having been focused on getting the regular patches correct. I will study that again and see how I can salvage those boundary patches.

Thanks again for all your help!

**Comment by barfowl** [comment]
Closing this all all issues and questions have been addressed.  Please open new issues for any points here that might warrant further discussion.  Thanks
