### ISSUE TITLE
Selective Subdivision.

### ISSUE THREAD

**Issue by VadiMysore** [PixarAnimationStudios/OpenSubdiv#1163]
Hi there!
I am prototyping the new sparse patch table feature in OpenSubDiv 3.4 release. I only want to adaptively subdivide a subset of a large number of base mesh faces. 

I set up everything as shown in the example far_tutorial_5_2.cpp. The only difference with the test case of the tutorial is that mine is a solid cube with each of its 6 faces split into a grid of 3X3 faces.

The patches generated by local subdivision do not seem to match the expectation. Very bad results are produced. I am graphically presenting the test case below. All the details are there in the image attached. Will this case be ideal for selective subdivision of a group of faces of a larger base mesh? Also, we are extracting patches from the patch table and fitting uniform bi-cubic, b-spline surfaces for each one of them. 

![LocalSubdvision](https://user-images.githubusercontent.com/24560022/68065770-cbefec00-fcfb-11e9-9ba8-7299e71f1de1.jpg)

The result of subdividing these faces is shown below. I have left out the patches that we could not fit a b-spline surface to. What could be wrong? I am ready to send the data, if needed, in any format.

![LocalSubdivisionResult](https://user-images.githubusercontent.com/24560022/68066673-aff34700-fd09-11e9-997d-08e92f84aba9.jpg)

Thanks,
Vadiraj

**Comment by jilliene** [comment]
Filed as internal issue #OSD-306

**Comment by VadiMysore** [comment]
I resolved this issue myself. Closing the same.

**Comment by davidgyu** [comment]
Thanks for the update, good to hear you've figured it out.
