### ISSUE TITLE
 Expose a flag to build opensubdiv as a _static_ library

### ISSUE THREAD

**Issue by pberto** [PixarAnimationStudios/OpenSubdiv#1169]
Please expose a flag to build opensubdiv ONLY as a static library. Currently both static and dynamics are built and we have to patch some files in order to do so and it's a bit inconvenient. Building as static should be exposed in the make process, something like `-DBUILD_SHARED_LIBS=OFF` would be perfect. Thanks!

**Comment by jilliene** [comment]
Filed as internal issue #OSD-314

**Comment by davidgyu** [comment]
This has now been addressed in the dev branch. Thanks!

**Comment by pberto** [comment]
Thank you.
