### ISSUE TITLE
Intermittent build failures on MacOS during framework creation

### ISSUE THREAD

**Issue by sunyab** [PixarAnimationStudios/OpenSubdiv#1194]
Building OSD on MacOS occasionally fails with errors like the following:

> cd /Users/usdonmac/Projects/usd/sunya/osd_test/build/OpenSubdiv-3_3_3/opensubdiv && /Applications/CMake.app/Contents/bin/cmake -E cmake_symlink_library ../lib/libosdGPU.3.\
3.3.dylib ../lib/libosdGPU.3.3.3.dylib ../lib/libosdGPU.dylib
cmake -E touch_nocreate: failed to update "lib/OpenSubdiv.framework/OpenSubdiv".
make[2]: *** [lib/OpenSubdiv.framework/OpenSubdiv] Error 1
make[1]: *** [opensubdiv/CMakeFiles/osd_static_framework.dir/all] Error 2

Looking through the full log (attached), it appears that the build is trying to write both the static and dynamic libraries to the same file in the framework:

> [100%] Linking CXX shared library ../lib/libosdGPU.dylib
[100%] Linking CXX static library ../lib/OpenSubdiv.framework/OpenSubdiv
[100%] Linking CXX static library ../lib/libosdGPU.a
[100%] Linking CXX shared library ../lib/OpenSubdiv.framework/OpenSubdiv

My guess is that the build may be trying to write to the same file concurrently, leading to the error above.

I've reproduced this on 3.3.0 and the 3.4.1+ release candidates when building with make using -j 12 but not with -j1.

**Comment by meshula** [comment]
The same issue exists for debug versus release builds, which is especially problematic on Windows. Locally, for my Windows OSD builds I add this line: 

```
set(CMAKE_DEBUG_POSTFIX _d)
```
In addition to appending a _d, I suggest OpenSubdiv should go all the way, as USD has done, appending s for static.

**Comment by davidgyu** [comment]
Good suggestions!

**Comment by jilliene** [comment]
Filed as internal issue #OSD-322

**Comment by davidgyu** [comment]
Fixed by #1214 so that parallel builds and static frameworks are now working. There's still more we can do to improve debug vs release but we will defer for now pending additional build system improvements.
