### ISSUE TITLE
enable opensubdiv on centos stream meet the python didn't match

### ISSUE THREAD

**Issue by guangli0510** [PixarAnimationStudios/OpenSubdiv#1197]
Hi all,
when i enable opensubdiv on centos stream, i met the following issues:
cd /home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/cmake-build/documentation && /usr/bin/python /home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/documentation/processTutorials.py /home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/tutorials/far/tutorial_5_2/far_tutorial_5_2.cpp /home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/cmake-build/documentation/far_tutorial_5_2.rst far/tutorial_5_2/far_tutorial_5_2.cpp
  File "/home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/documentation/processTutorials.py", line 36
    print "Could not read file \'"+inputfile+"\'"
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Could not read file \'"+inputfile+"\'")?
make[2]: *** [documentation/CMakeFiles/far_tutorial_5_2_far_tutorial_5_2.cpp.dir/build.make:71: documentation/far_tutorial_5_2.rst] Error 1
make[2]: Leaving directory '/home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/cmake-build'
make[1]: *** [CMakeFiles/Makefile2:5425: documentation/CMakeFiles/far_tutorial_5_2_far_tutorial_5_2.cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/cmake-build'
[ 36%] Generating far_tutorial_4_1.rst
cd /home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/cmake-build/documentation && /usr/bin/python /home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/documentation/processTutorials.py /home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/tutorials/far/tutorial_4_1/far_tutorial_4_1.cpp /home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/cmake-build/documentation/far_tutorial_4_1.rst far/tutorial_4_1/far_tutorial_4_1.cpp
  File "/home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/documentation/processTutorials.py", line 36
    print "Could not read file \'"+inputfile+"\'"
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Could not read file \'"+inputfile+"\'")?
make[2]: *** [documentation/CMakeFiles/far_tutorial_4_1_far_tutorial_4_1.cpp.dir/build.make:71: documentation/far_tutorial_4_1.rst] Error 1
make[2]: Leaving directory '/home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/cmake-build'
make[1]: *** [CMakeFiles/Makefile2:5610: documentation/CMakeFiles/far_tutorial_4_1_far_tutorial_4_1.cpp.dir/all] Error 2
make[2]: Entering directory '/home/pnp/blender/opensubdiv/BUILD/OpenSubdiv-3_4_0/cmake-build'

I think this is caused by python3.6 not python2. Did you have plan to python3?

**Comment by guangli0510** [comment]
I competed the patch porting, the patch is as below:
From 18094ecd0264964e36e84731cf621ee81ca8fa6b Mon Sep 17 00:00:00 2001
From: guanglil <guangli.li@intel.com>
Date: Thu, 14 May 2020 10:39:31 -0400
Subject: [PATCH] port it to Python3
---
 documentation/processHtml.py      | 25 +++++++++++++------------
 documentation/processTutorials.py |  6 +++---
 2 files changed, 16 insertions(+), 15 deletions(-)

diff --git a/documentation/processHtml.py b/documentation/processHtml.py
index 1a81df5..53ae29f 100755
--- a/documentation/processHtml.py
+++ b/documentation/processHtml.py
@@ -27,11 +27,12 @@ import os
 import sys
 import string
 import re
-import HTMLParser
+from html.parser import HTMLParser
 
-class HtmlToTextParser(HTMLParser.HTMLParser):
+class HtmlToTextParser(HTMLParser):
     def __init__(self):
-        HTMLParser.HTMLParser.__init__(self)
+        #HTMLParser.HTMLParser.__init__(self)
+        HTMLParser.__init__(self)
         self.m_text = []
         self.m_inTitle = False
         self.m_inScript = False
@@ -89,10 +90,10 @@ def ReadNavigationTemplate( filePath ):
     try:
         navFile = open( filePath, "r")
     except IOError:
-        print "Could not open file \'"+filePath+"\'"
+        print("Could not open file \'"+filePath+"\'")
     
     with navFile:
-        print "Navigation template: \'"+filePath+"\'"
+        print("Navigation template: \'"+filePath+"\'")
         navHtml = navFile.read()
         navHtml = StripHTMLComments(navHtml)
         navFile.close()
@@ -109,7 +110,7 @@ def WriteIndexFile( outputFile, content ):
     except:
         pass
 
-    print "Creating Search-Index File : \""+outputFile+"\""
+    print("Creating Search-Index File : \""+outputFile+"\"")
 
     f = open(outputFile, "w")
     f.write(content)
@@ -117,7 +118,7 @@ def WriteIndexFile( outputFile, content ):
 
 #-------------------------------------------------------------------------------
 def Usage():
-    print str(sys.argv[0])+" <input directory> <output directory> <html template>"
+    print(str(sys.argv[0])+" <input directory> <output directory> <html template>")
     exit(1);
 
 
@@ -132,7 +133,7 @@ navTemplate = str(sys.argv[2])
     
 navHtml = ReadNavigationTemplate( navTemplate )
 
-print "Scanning : \'"+rootDir+"\'"
+print("Scanning : \'"+rootDir+"\'")
 
 searchIndex = 'var tipuesearch = { "pages": [ '
 
@@ -172,22 +173,22 @@ for root, dirs, files in os.walk(rootDir):
 
             # if necessary, insert navigation html
             if (not parser.HasNavigationSection()):
-                loc = string.find(html,"<body>")
+                loc = str.find(html,"<body>")
                 html = html[:loc+6] + navHtml + html[loc+6:]
 
                 msg += "added navigation"
 
             # replace the article title placeholder with the real title
             if title:
-                html = string.replace(html,"OSD_ARTICLE_TITLE", title)
+                html = str.replace(html,"OSD_ARTICLE_TITLE", title)
             else:
-                html = string.replace(html,"OSD_ARTICLE_TITLE", "")
+                html = str.replace(html,"OSD_ARTICLE_TITLE", "")
 
             f.seek(0)
             f.write(html)
             f.close()
 
-            print msg
+            print(msg)
 
 searchIndex = searchIndex + "]};"
 
diff --git a/documentation/processTutorials.py b/documentation/processTutorials.py
index e632915..30d3e71 100755
--- a/documentation/processTutorials.py
+++ b/documentation/processTutorials.py
@@ -33,7 +33,7 @@ def ReadFile(inputfile):
     try:
         f = open( inputfile, "r")
     except IOError:
-        print "Could not read file \'"+inputfile+"\'"
+        print("Could not read file \'"+inputfile+"\'")
     content = f.read()
     f.close()
     return content
@@ -48,7 +48,7 @@ def WriteToFile(outputfile, content):
     try:
         f = open(outputfile, "w")
     except IOError:
-        print "Could not write file \'"+outputfile+"\'"
+        print("Could not write file \'"+outputfile+"\'")
     f.write(content)
     f.close()
 
@@ -85,7 +85,7 @@ def Process(srcfile, title):
 
 #-------------------------------------------------------------------------------
 def Usage():
-    print str(sys.argv[0])+" <input file> <output file> <title>"
+    print(str(sys.argv[0])+" <input file> <output file> <title>")
     exit(1);
 
 
-- 
2.18.2

**Comment by jtran56** [comment]
Filed as internal issue #OSD-325.

**Comment by davidgyu** [comment]
This has been fixed by #1265 Thanks!
