### ISSUE TITLE
A formula problem of your thesis

### ISSUE THREAD

**Issue by Jerryhangod** [PixarAnimationStudios/OpenSubdiv#1199]
I am a graduate student from Nanjing University, China, engaged in computer work. I read your thesis named "Modeling and Data-Driven Parameter Estimation for Woven Fabrics, 2017", and have a problem about the derivation of equation 6 in "Simulation of nonlinear Kirchhoff-Love thin shells using subdivision finite elements". Can you tell me the exact derivation of the equation? 
       Thank you!

**Comment by c64kernal** [comment]
Apologies, though this question is best directed at the authors of the paper, and is unrelated to this project.
