### ISSUE TITLE
Parallel implementation of Osd::Mesh()?

### ISSUE THREAD

**Issue by kvanhoey** [PixarAnimationStudios/OpenSubdiv#1200]
Hello,

We have run a subdivision code of OSD (essentially, the code of the glViewer) using the OpenMP and TBB backends and have noticed that they both seem to fail at balancing workload on multiple threads.

For example, when running the following code
```
// precomputation of the subdivision surface -- we expect this to run on multiple threads
new Osd::Mesh<Osd::CpuGLVertexBuffer,
              Far::StencilTable,
              Osd::OmpEvaluator,
              Osd::GLPatchTable>(
                                 refiner,
                                 numVertexElements,
                                 0,
                                 level, bits)
```
we consistently see activity on a single thread during subdivision, which makes us believe that OpenSubdiv does not currently have a parallel CPU implementation. Is this indeed the case or are we doing something wrong ?

Many thanks for your help.

Kenneth

**Comment by jtran56** [comment]
Filed as internal issue #OSD-329

**Comment by c64kernal** [comment]
Hi Kenneth, the intention is definitely for OpenSubdiv to have parallel CPU implementations, though it's possible that something has broken. Both TBB and OpenMP kernels should make use of multiple cores -- though the configuration of how many Cores is usually specific to the host system. The TBB evaluator has a SetNumThreads() though that one again is at the mercy of what TBB has already been initialized to before, if it is hosted in an application that already sets this up. Hope this helps give you a clue for further debugging!

**Comment by barfowl** [comment]
As George says, the TBB and OMP evaluators are designed to run on multiple threads, and there are public methods that should control it.  But the construction of the tables that these evaluation classes use -- created within the Osd::Mesh<> constructor -- is single-threaded.  The design intention of these classes is to construct tables designed for rapid evaluation once (single-threaded) and evaluate many times (multi-threaded).  So if the usage that you are assessing is dominated by construction, you will see poor thread utilization.  The more you re-evaluate after construction, the more you should see activity on the expected number of threads.

**Comment by davidgyu** [comment]
In addition to what George and Barry have said, you might be interested to take a look at [far_tutorial_5_2](https://github.com/PixarAnimationStudios/OpenSubdiv/blob/master/tutorials/far/tutorial_5_2/far_tutorial_5_2.cpp) which shows a way to organize topological refinement and construction of tables in a way that can be distributed across parallel tasks.

**Comment by kvanhoey** [comment]
Hi all three of you. Thank you for your replies. This makes sense indeed. Especially Barry's comment on the fact that the data structure is built so that there is a (relatively) slow computation in favor of quick parallel runtime performance was enlightening. 
I'll take a look at the suggested tutorial, as well as some research papers on how table construction is best achieved (is there a precise reference that was implemented or is it OpenSubdiv's own making ?).

Again, many thanks.

**Comment by barfowl** [comment]
I missed the final question in your closing comment earlier...  There is no precise reference on the tables that OpenSubdiv uses -- they are of OpenSubdiv's own making.
Unfortunately, there are a few different tables that are used as building blocks for different purposes, and once you step away from Osd::Mesh, you are left to assemble and manage them yourself.  Hopefully the far_tutorials help.
Regarding the tables, the StencilTable is the simplest to apply as it has factored limit points, tangents, etc. down to simple linear combinations of base vertices.  It makes repeated application efficient and easily threaded, but unfortunately it is the most costly table to build.  I avoid using StencilTables as much as possible for one-time subdivision or tessellation.  If you do need/want them, you can build several StencilTables for different parts of your mesh on multiple threads, similar to the far_tutorial that David cited.

**Comment by kvanhoey** [comment]
Thank you Barry. I think I can figure out the best scenario for my needs now. Thanks for the great reactivity of you and your colleagues.
