### ISSUE TITLE
Efficient, Fair Interpolation Using Catmull-Clark Surfaces

### ISSUE THREAD

**Issue by roquo** [PixarAnimationStudios/OpenSubdiv#1202]
On the [reference page](http://graphics.pixar.com/opensubdiv/docs/references.html) of OpenSubdiv is the paper "Efficient, Fair Interpolation using Catmull-Clark Surfaces" mentioned. I wanted to ask if this algorithm of interpolating a new control cage depending on the initial control cage so that the new control cage subdivides into the original mesh is implemented in the OpenSubdiv library? 

I was not sure where to ask this question. If this question is inappropriate here, please close the Issue. Thanks!

**Comment by jilliene** [comment]
Filed as internal issue #OSD-332

**Comment by davidgyu** [comment]
OpenSubdiv does not have an implementation of the method described in that paper.

However, the computed control mesh resulting from the method described in that paper is a Catmull-Clark subdivision surface and OpenSubdiv can be used to process that resulting mesh, e.g. to evaluate positions and derivatives on the limit surface, or to tessellate the mesh for rendering, etc.

Thanks for asking!
