### ISSUE TITLE
[Website/Docs] Example videos in not shown (Chrome/FF/macoS)

### ISSUE THREAD

**Issue by virtualritz** [PixarAnimationStudios/OpenSubdiv#1225]
E.g.
https://graphics.pixar.com/opensubdiv/docs/mod_notes.html#additional-resources
https://graphics.pixar.com/opensubdiv/docs/additional_resources.html#videos

All videos are not shown for me on latest stable Firefox or Chrome on macOS.

**Comment by davidgyu** [comment]
Seeing this with Safari as well and also on Linux. The target videos are still be there, but the links aren't presenting as expected. Taking a closer look. Thanks!

**Comment by jilliene** [comment]
Filed as internal issue #OSD-351

**Comment by davidgyu** [comment]
Fixed in dev and pushed to the doc server. Thanks!
