### ISSUE TITLE
Memory leak in tutorial

### ISSUE THREAD

**Issue by AlvaroFS** [PixarAnimationStudios/OpenSubdiv#1226]
https://github.com/PixarAnimationStudios/OpenSubdiv/blob/ff76e0f2dc9c9202b7d2f965f264bfd6f41866d5/tutorials/far/tutorial_2_3/far_tutorial_2_3.cpp#L323

Variable `refiner` is never deleted.

**Comment by davidgyu** [comment]
Good catch! Thanks!

**Comment by jilliene** [comment]
Filed as internal issue #OSD-352

**Comment by barfowl** [comment]
Addressed by #1251
