### ISSUE TITLE
d3d11ComputeEvaluator.cpp does not compile with Visual Studio 2022 preview 1

### ISSUE THREAD

**Issue by wayne-arnold-adsk** [PixarAnimationStudios/OpenSubdiv#1232]
OpenSubdiv does not build with Visual Studio 2022. d3d11ComputeEvaluator.cpp

    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(239): error C2220: the following warning is treated as an error
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(239): warning C5246: 'defines': the initialization of a subobject should be wrapped in braces
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(239): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(240): warning C5246: 'defines': the initialization of a subobject should be wrapped in braces
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(240): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(241): warning C5246: 'defines': the initialization of a subobject should be wrapped in braces
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(241): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(242): warning C5246: 'defines': the initialization of a subobject should be wrapped in braces
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(242): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(243): warning C5246: 'defines': the initialization of a subobject should be wrapped in braces
    D:\branch\maya\worktrees\main\Maya\src\Components\ExternalLibraries\OpenSubdiv\OpenSubdiv\opensubdiv\osd\d3d11ComputeEvaluator.cpp(243): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings

search for C5246 in
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/overview/cpp-conformance-improvements.md

from https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-160

/Wv[:version]	Displays only warnings introduced in the version compiler version and earlier. You can use this option to suppress new warnings in code when you migrate to a newer version of the compiler. It lets you maintain your existing build process while you fix them. The optional parameter version takes the form nn[.mm[.bbbbb]], where nn is the major version number, mm is the optional minor version number, and bbbbb is the optional build number of the compiler. For example, use /Wv:17 to display only warnings introduced in Visual Studio 2012 (major version 17) or earlier. That is, it displays warnings from any version of the compiler that has a major version number of 17 or less. It suppresses warnings introduced in Visual Studio 2013 (major version 18) and later. By default, /Wv uses the current compiler version number, and no warnings are suppressed. For information about which warnings are suppressed by compiler version, see Compiler warnings by compiler version.

adding {} around the pairs allows the build to complete

    D3D_SHADER_MACRO defines[] =
        { {"LENGTH", lengthValue.c_str()},
          {"SRC_STRIDE", srcStrideValue.c_str()},
          {"DST_STRIDE", dstStrideValue.c_str()},
          {"WORK_GROUP_SIZE", workgroupSizeValue.c_str()},
          {0, 0} };

**Comment by davidgyu** [comment]
Yes, it looks like the C5246 warning about elided braces is new in VS2022.

This warning is disabled by default and we don't hit it in our test builds using VS2022 Preview 1 and CMake 3.21.0-rc2 since OpenSubdiv is configured to use /W3 (recommended for production code).

The suggested fix seems reasonable for portability and clarity (especially since the class being initialized is defined elsewhere in the d3d headers), though the standard does allow braces to be elided in this context.

**Comment by jilliene** [comment]
Filed as internal issue #OSD-357

**Comment by davidgyu** [comment]
Fixed by #1239
