### ISSUE TITLE
OpenSubdiv "Unresolved External Symbol" trying to compile on Windows 10 

### ISSUE THREAD

**Issue by rjmigliori** [PixarAnimationStudios/OpenSubdiv#1245]
**Dealing with the following error:** 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: __cdecl OpenSubdiv::v3_4_4::Far::TopologyDescriptor::TopologyDescriptor(void)" (??0TopologyDescriptor@Far@v3_4_4@OpenSubdiv@@QEAA@XZ)	pyOpenSubdiv	C:\Users\username>\source\repos\pyOpenSubdiv\pyOpenSubdiv\Source.obj	1	
```

Context below. 

Prerequisites: 
- Using Visual Studio 17 2022 with the C/C++ development package installed (e.g. msvc compiler). 
- Installed CMake, added to path. 
- Downloaded GLFW Windows 64 bit binares (https://www.glfw.org/download.html)
- Copied contents of `...\glfw-3.3.7.bin.WIN64\glfw-3.3.7.bin.WIN64\lib-vc2022` into `...\glfw-3.3.7.bin.WIN64\glfw-3.3.7.bin.WIN64\lib`
- Pulled OpenSubdiv repo 
- mkdir build, cd build 
- Run first build command 
```cmake ^ -G "Visual Studio 17 2022" ^ -D NO_PTEX=1 -D NO_DOC=1 ^ -D NO_OMP=1 -D NO_TBB=1 -D NO_CUDA=1 -D NO_OPENCL=1 -D NO_CLEW=1 ^ -D "GLFW_LOCATION=C:/Users/<username>/Desktop/cpp/glfw-3.3.7.bin.WIN64/glfw-3.3.7.bin.WIN64" ^ ..```
- Output: 
```
PS C:\Users\<username>\Desktop\cpp\OpenSubdiv\build> cmake ^ -G "Visual Studio 17 2022" ^ -D NO_PTEX=1 -D NO_DOC=1 ^ -D NO_OMP=1 -D NO_TBB=1 -D NO_CUDA=1 -D NO_OPENCL=1 -D NO_CLEW=1 ^ -D "GLFW_LOCATION=C:/Users/<username>/Desktop/cpp/glfw-3.3.7.bin.WIN64/glfw-3.3.7.bin.WIN64" ^ ..
CMake Warning:
  Ignoring extra path from command line:

   "C:/Users/<username>/Desktop/cpp/OpenSubdiv/build/^"


-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.32.31332.0
-- The CXX compiler identification is MSVC 19.32.31332.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:27 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Compiling OpenSubdiv version v3_4_4
-- Using cmake version 3.24.0-rc2
-- Found OpenGL: opengl32
-- Found GLFW: C:/Users/<username>/Desktop/cpp/glfw-3.3.7.bin.WIN64/glfw-3.3.7.bin.WIN64/include (found suitable version "3.3.7", minimum required is "3.0.0")
-- Found DXSDK: C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/um
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/<username>/Desktop/cpp/OpenSubdiv/build
```
- Run build install command: 
```
cmake --build . --config Release --target install 
```
Which seems to work fine except for this part: 
```
...
  Generating Code...
  osd_gpu_obj.vcxproj -> C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\opensubdiv\osd\osd_gpu_obj.dir\Release\osd_gpu
  _obj.lib
  version.cpp
  osd_static_gpu.vcxproj -> C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\lib\Release\osdGPU.lib
  Generating shader.gen.h
  dxviewer.cpp
dxviewer.obj : error LNK2019: unresolved external symbol D3D11CreateDeviceAndSwapChain referenced in function "bool __c
decl initD3D11(struct HWND__ *)" (?initD3D11@@YA_NPEAUHWND__@@@Z) [C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\exam
ples\dxViewer\dxViewer.vcxproj]
d3d11Utils.obj : error LNK2019: unresolved external symbol D3DCompile referenced in function "struct ID3D10Blob * __cde
cl D3D11Utils::CompileShader(char const *,char const *,char const *)" (?CompileShader@D3D11Utils@@YAPEAUID3D10Blob@@PEB
D00@Z) [C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\examples\dxViewer\dxViewer.vcxproj]
d3d11ShaderCache.obj : error LNK2001: unresolved external symbol D3DCompile [C:\Users\<username>\Desktop\cpp\OpenSubdiv\
build\examples\dxViewer\dxViewer.vcxproj]
osdGPU.lib(d3d11ComputeEvaluator.obj) : error LNK2001: unresolved external symbol D3DCompile [C:\Users\<username>\Deskto
p\cpp\OpenSubdiv\build\examples\dxViewer\dxViewer.vcxproj]
osdGPU.lib(d3d11ComputeEvaluator.obj) : error LNK2019: unresolved external symbol D3DReflect referenced in function "pu
blic: bool __cdecl OpenSubdiv::v3_4_4::Osd::D3D11ComputeEvaluator::Compile(struct OpenSubdiv::v3_4_4::Osd::BufferDescri
ptor const &,struct OpenSubdiv::v3_4_4::Osd::BufferDescriptor const &,struct ID3D11DeviceContext *)" (?Compile@D3D11Com
puteEvaluator@Osd@v3_4_4@OpenSubdiv@@QEAA_NAEBUBufferDescriptor@234@0PEAUID3D11DeviceContext@@@Z) [C:\Users\<username>\D
esktop\cpp\OpenSubdiv\build\examples\dxViewer\dxViewer.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86\d3d11.lib : warning LNK4272: library machine type 'x86'
conflicts with target machine type 'x64' [C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\examples\dxViewer\dxViewer.vc
xproj]
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86\d3dcompiler.lib : warning LNK4272: library machine type
'x86' conflicts with target machine type 'x64' [C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\examples\dxViewer\dxVie
wer.vcxproj]
C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\bin\Release\dxViewer.exe : fatal error LNK1120: 3 unresolved externals
[C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\examples\dxViewer\dxViewer.vcxproj]
...
```

Then, I have a basic Visual Studio C++ project with the C/C++ addition include directories: 
```
C:\Users\<username>\Desktop\cpp\OpenSubdiv
C:\Users\<username>\Desktop\cpp\boost_1_79_0
C:\Users\<username>\Desktop\cpp\glfw-3.3.7.bin.WIN64\glfw-3.3.7.bin.WIN64\include
C:\Users\<username>\AppData\Local\Programs\Python\Python310\include
%(AdditionalIncludeDirectories)
```

And for the Linker, the following additional include libraries: 
```
C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\lib\
C:\Users\<username>\Desktop\cpp\boost_1_79_0\bin\x64\lib
C:\Users\<username>\AppData\Local\Programs\Python\Python310\DLLs
C:\Users\<username>\AppData\Local\Programs\Python\Python310\Lib
C:\Users\<username>\AppData\Local\Programs\Python\Python310\libs
C:\Users\<username>\AppData\Local\Programs\Python\Python310\tcl
%(AdditionalLibraryDirectories)
```

Finally, when I try to compile this code (build the project in visual studio)

```

#define BOOST_PYTHON_STATIC_LIB
#include <iostream>
#include <boost/python.hpp>


#define _USE_MATH_DEFINES
#include <math.h>

// #include <GLFW/glfw3.h>
#include <opensubdiv/far/topologyDescriptor.h>
#include <opensubdiv/far/primvarRefiner.h>



using namespace OpenSubdiv;
char const* test_function() {
	return "Hello from C++";
	typedef Far::TopologyDescriptor Descriptor;
	Descriptor desc;
}

BOOST_PYTHON_MODULE(Project1) {
	boost::python::def("test_function", test_function);
}

int main(void) {
	return 0; 
}
```

**I get the following error:** 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: __cdecl OpenSubdiv::v3_4_4::Far::TopologyDescriptor::TopologyDescriptor(void)" (??0TopologyDescriptor@Far@v3_4_4@OpenSubdiv@@QEAA@XZ)	pyOpenSubdiv	C:\Users\username>\source\repos\pyOpenSubdiv\pyOpenSubdiv\Source.obj	1	
```

Along with a huge number of warnings, which I'm also not sure what to do about. 

I don't know how to resolve this. Can anyone help? Please let me know if there is any additional information I can provide. Note that the code compiles fine with the libraries only included, it only fails when I try to use them, e.g. instance a `TopologyDescriptor`.

**Comment by meshula** [comment]
It looks like you are building for x64, but trying to link against a 32 bit windows sdk, instead of the 64 bit one.

```
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86\d3dcompiler.lib : warning LNK4272: library machine type
'x86' conflicts with target machine type 'x64' [C:\Users\<username>\Desktop\cpp\OpenSubdiv\build\examples\dxViewer\dxVie
wer.vcxproj]
```

On my machine, the x64 libraries are adjacent to the x86 libraries ~ your path is 

`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86`

mine is

`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64`

**Comment by rjmigliori** [comment]
I see. can you suggest a fix? I have that path on my computer ( `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64`). Is there a way to tell OpenSubdiv to build using the 64 bit libraries? Is this an environment variable issue, or maybe not the right commands being passed into cmake?

**Comment by meshula** [comment]
The usual reason cmake makes x86 choices, is if you weren't running the `x64 Native Tools Command Prompt` shell (or running the vcvars batch file associated with that shell) when you configured the build, although it is trying to build x64 OpenSubdiv, so that might not be the problem. Could you double check that you are in an x64 native prompt, and if you are, could you attach your CMakeCache.txt file?

**Comment by rjmigliori** [comment]
[CMakeCache.txt](https://github.com/PixarAnimationStudios/OpenSubdiv/files/9004156/CMakeCache.txt)

I'm building in powershell, and I checked that I'm running a 64-bit instance of it. I could try CMD prompt?

I've attached my cmake cache file. Let me know if you have trouble reading it.

**Comment by meshula** [comment]
If you search within it, it confirms that cmake has picked the incorrect windows sdk. As a quick test, changing all the `\um\x86` to `\um\x64` and then running `cmake .` in the CMakeCache.txt's directory will likely get you building, but in a very inconvenient way since you'd have to correct the error manually any time you need to regenerate the build.

I have locally verified the same issue under powershell and under an x64 native command prompt.

**Comment by meshula** [comment]
If you search within it, it confirms that cmake has picked the incorrect windows sdk.

Delete your build directory and run this way ~

`cmake /path/to/OpenSubdiv -DCMAKE_GENERATOR_PLATFORM=x64`

and you'll get the correct result.

**Comment by rjmigliori** [comment]
Alright that got the install to work properly, which is great! But I'm still getting the same compile error `LNK2001	unresolved external symbol "public: __cdecl OpenSubdiv::v3_4_4::Far::TopologyDescriptor::TopologyDescriptor(void)" (??0TopologyDescriptor@Far@v3_4_4@OpenSubdiv@@QEAA@XZ)	pyOpenSubdiv	C:\Users\username>\source\repos\pyOpenSubdiv\pyOpenSubdiv\Source.obj`

These are the exact commands I ran, in an administrator powershell 

```cmake ^ -DCMAKE_GENERATOR_PLATFORM=x64 -G "Visual Studio 17 2022" ^ -D NO_PTEX=1 -D NO_DOC=1 ^ -D NO_OMP=1 -D NO_TBB=1 -D NO_CUDA=1 -D NO_OPENCL=1 -D NO_CLEW=1 ^ -D "GLFW_LOCATION=C:/Users/rmigliori/Desktop/cpp/glfw-3.3.7.bin.WIN64/glfw-3.3.7.bin.WIN64" ^ ..```

```cmake --build . --config Release --target install ```

Maybe the second cmake --build needs a -DCMAKE_GENERATOR_PLATFORM, but I'm not sure where to put it?

**Comment by rjmigliori** [comment]
I solved the problem, I was missing osdCPU.lib and osdGPU.lib in the Visual Studio Linker "Input Additional Dependencies." [See e.g. this SE answer.](https://stackoverflow.com/a/42867190/2391876)

What a relief. Thank you so much for the help.
