### ISSUE TITLE
No /ompEvaluator.h generated

### ISSUE THREAD

**Issue by derrick-xwp** [PixarAnimationStudios/OpenSubdiv#1248]

**Comment by davidgyu** [comment]
Filed as internal issue #OSD-384

**Comment by davidgyu** [comment]
Can you tell us more about the problem you are having?

On platforms where OpenMP is detected and enabled I'm seeing ompEvaluator.h installed correctly, e.g. Windows VS2019, Red Hat Enterprise Linux.

**Comment by davidgyu** [comment]
We've verified that this is working correctly in our testing. Marking this closed.
Please reopen or file a new ticket with additional information if this is still a problem for you. Thanks!
