### ISSUE TITLE
bfr_evaluate : failure on dev branch

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#1260]
OS : CentOS Linux release 7.9.2009 (Core)
SCL: GCC 9.3.1

```
  29 of 60:  'catmark_chaikin1'
'catmark_chaikin1':
		POS diffs:     1 faces, max delta P  = 0.00122643
```

commit tag
```
commit 698c7242bbf68e497feb5f9549dd40e494d1d269
Merge: 62e75e4 1b773c0
Author: David G Yu <davidgyu@gmail.com>
Date:   Thu Sep 8 10:26:53 2022 -0700

    Merge pull request #1259 from davidgyu/dev_obsolete_ci
    
    Removed appveyor and travis-ci scripts
```

**Comment by barfowl** [comment]
The failure listed is a known and accepted deviation but should not be triggering any failures with existing scripts. Are you running the bfr_evaluate regression directly and without command line arguments?

Assuming you are, it does not provide good coverage on its own and does include known deviations -- so it is expected to fail. We run it with additional arguments to cover more functionality in our CI builds and to exclude known deviations.  So if you really want to run bfr_evaluate to verify a build, you should run the full set of tests we define for it, e.g. "ctest -R bfr_evaluate".

That being said, the fact that running it without arguments does trigger a failure is likely going to cause confusion in future, so I'll look into making it successful by default.

Thanks

**Comment by barfowl** [comment]
@nyue, I just merged pull request #1262 that will hopefully address this. If so, please close this issue, otherwise we'll keep it open to deal with anything else.

**Comment by nyue** [comment]
I did a pull and came across a CMake configuration issue and have lodge #1263 

Once that is resolved, I will build and test again and close this in due course.

Thank you @barfowl

**Comment by barfowl** [comment]
@nyue, I noted in your new issue #1263 that the CMake error we are now getting can be avoided by not building the documentation.

So by building without the docs, you can independently verify if the issue raised here for bfr_evaluate has been addressed.

Thanks

**Comment by nyue** [comment]
Built without documentation. Retested bfr_evaluate, all good.
