### ISSUE TITLE
v3.5.0 OpenSubdivConfig.cmake usage

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#1278]
I am building a simple example to learn about the cmake config file shipped with v3.5.0

I can't seem to get it to include the include path

Error output
```
[ 50%] Building CXX object CMakeFiles/check_linkage.dir/check_linkage.cpp.o
/data2/nyue/projects/OpenSubdiv/OpenSubdivBfr/OpenSubdivBfr_git/check_linkage.cpp:1:10: fatal error: opensubdiv/far/topologyRefiner.h: No such file or directory
 #include <opensubdiv/far/topologyRefiner.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/check_linkage.dir/build.make:75: recipe for target 'CMakeFiles/check_linkage.dir/check_linkage.cpp.o' failed
make[2]: *** [CMakeFiles/check_linkage.dir/check_linkage.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/check_linkage.dir/all' failed
make[1]: *** [CMakeFiles/check_linkage.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.12)

project(bfr)

find_package(OpenSubdiv CONFIG REQUIRED)

add_executable(check_linkage
  check_linkage.cpp
  )

target_link_libraries(check_linkage
  OpenSubdiv::osdCPU_static
  OpenSubdiv::osdGPU_static
  )
```

Source file
```
#include <opensubdiv/far/topologyRefiner.h>
#include <opensubdiv/bfr/refinerSurfaceFactory.h>
#include <opensubdiv/bfr/surface.h>

#include <vector>
#include <string>
#include <cstring>
#include <cstdio>

int main()
{
	return 0;
}
```

**Comment by davidgyu** [comment]
That looks pretty good, but I think you still need to specify the include path,
i.e. does it work if you add:
    include_directories(${OpenSubdiv_INCLUDE_DIR})

**Comment by nyue** [comment]
My understanding of using the config approach is to minimise include path pollution and promote per target includes

Other package's config I have use has include path included in the config target so that when you link to it, the include path is provided to the compile target.

I am no CMake expert so I may have been using CMake wrongly but that is the behaviour I have grown accustom to with other configs

For now, I will use ${OpenSubdiv_INCLUDE_DIR}

Thank you @davidgyu

**Comment by davidgyu** [comment]
Thanks for confirming @nyue!

**Comment by davidgyu** [comment]
This passed in our testing, but there may be something more here, and we'll check to make sure our configs are being created correctly.

**Comment by davidgyu** [comment]
Filed as internal issue #OSD-390
