### ISSUE TITLE
bfr: GatherControlPoints - vertex ordering ?

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#1282]
Hi,

  I am studying the output from a Surface::GatherControlPoints() method and wondering where I can read more about the layout of the output values

  I am experimenting with a simple cube with facevarying UVs as input

```
        //
        //  Limit stencils can be applied using the control points in a
        //  local array or directy from the mesh. Both are shown here, so
        //  if using the local array, resize and populate it:
        //
        bool gatherControlPoints = true;
        if (gatherControlPoints) {
            faceControlPoints.resize(numControlPoints * 3);
            faceSurface.GatherControlPoints(meshVertexPositions.data(), 3,
                                            faceControlPoints.data(), 3);

			faceControlUVs.resize(numControlPoints * 2);
			faceSurface.GatherControlPoints(meshFaceVaryingUVs.data(), 2,
					faceControlUVs.data(), 2);

            for (auto i=0;i<numControlPoints;i++)
            {
            	fprintf(stderr,"%f,%f,%f [%f,%f]\n",
            			faceControlPoints[i*3],faceControlPoints[i*3+1],faceControlPoints[i*3+2],
						faceControlUVs[i*2],faceControlUVs[i*2+1]);
            }
        }
```

  I gather that each of the six faces of the cube becomes a faceSurface and it has 8 control points.

```
numControlPoints = 8
0.500000,-0.500000,-0.500000 [0.648950,0.982283]
0.500000,0.500000,-0.500000 [0.333333,0.666667]
0.500000,0.500000,0.500000 [0.000000,0.648950]
0.500000,-0.500000,0.500000 [0.315616,0.333333]
-0.500000,-0.500000,-0.500000 [0.648950,0.666667]
-0.500000,0.500000,-0.500000 [0.333333,0.982283]
-0.500000,0.500000,0.500000 [0.000000,0.333333]
-0.500000,-0.500000,0.500000 [0.315616,0.648950]
numControlPoints = 8
-0.500000,-0.500000,0.500000 [0.315616,0.648950]
-0.500000,0.500000,0.500000 [0.000000,0.333333]
-0.500000,0.500000,-0.500000 [0.333333,0.982283]
-0.500000,-0.500000,-0.500000 [0.648950,0.666667]
0.500000,-0.500000,0.500000 [0.315616,0.333333]
0.500000,0.500000,0.500000 [0.000000,0.648950]
0.500000,0.500000,-0.500000 [0.333333,0.666667]
0.500000,-0.500000,-0.500000 [0.648950,0.982283]
```

  Since the original cage only has 4 vertices, I am wondering if there is some algorithm to work out which indices I can use to match the original cage i.e. I can get the faceControlUVs or the faceControlPoints but which of them matches the 4 of the original cage ?

Cheers

**Comment by barfowl** [comment]
The ordering of the vertices involved, is intentionally not exposed or documented and you should NOT rely on it. Where in the set of control points the face-vertices are located depends on (and are tuned to) the underlying representation of the surface, so it varies for regular vs irregular regions, type of patch, etc.  We want the flexibility to change that ordering in future if internal improvements warrant it.

If there is a compelling case to know which control points correspond to the face-vertices, we can consider adding a method to Bfr::Surface to provide them in a future release.

**Comment by nyue** [comment]
I have a geometry creation workflow that make things a whole lot easier for me (procedural-ly) to be able to e.g. provide a give UV location in geometry mesh space (i.e. the geometry mesh's original UVs)

![image](https://user-images.githubusercontent.com/486172/194210171-75c38771-499d-4c52-af0b-4142629bdeb6.png)


For example, uv -> 0.5,0.5

I want some function/method to return to me .... oh, that will be Surface's face index 5, at it's local s,t space of about [0.4999,0.4998]

I will then use this surface index and s,t information to apply the stencil, get the limit position, du,dv and friends and voila, I can plant my favourite widget there.

The solution has to be fast cause I will end up doing 100,000s or millions of these (hair/fur/grass etc)

I want to plant the location via UV

With the exception of the stencil/limit calculation, I can do the maths outside of OpenSubdiv **but** the mesh face ordering and the Surface's face index order may not be the same, hence I still end up safer to cycle through the faces in OSD's bfr::Surface, which I can (all the tutorial already teach us how to do that)

However, when I reach a given face (for a given index), I have a source UV, I need to know if this source UV is **within** the face I am indexing, how do I do that? Let's query the given face's UV to do some basic in/out test

Right, the face has 8 control points .... which one do I use for the inRect test ? Ah!

This is where I am now :-)

**Comment by barfowl** [comment]
I'm jumping to the end of your message and may be overlooking a fine detail or two on the way...

    "Right, the face has 8 control points .... which one do I use for the inRect test ? Ah!"

Why use the Surface (or its Factory) to get this information when it's already available for the face of the mesh? The SurfaceFactory is not intended to replace the mesh or duplicate any of its data, but to provide enhanced functionality for the limit surface only. Since the "mesh" in the tutorial cases is a Far::TopologyRefiner, just use it to get the face-varying indices for the face (the factory retains and provides a reference to the mesh if needed).

**Comment by nyue** [comment]
Thank you @barfowl  for the suggestion on using Far::TopologyRefiner, I believe I have something suitable for further experimentation.

```
    {
    	int maxLevel = meshTopology.GetMaxLevel();
    	fprintf(stderr,"maxLevel = %d\n",maxLevel);

    	int numLevels = meshTopology.GetNumLevels();
    	fprintf(stderr,"numLevels = %d\n",numLevels);

    	{
    		const Vtr::internal::Level& level = meshTopology.getLevel(meshTopology.GetMaxLevel());
        	fprintf(stderr,"level.getNumFaces() = %d\n",level.getNumFaces());
        	int numFaces = level.getNumFaces();
        	for (auto faceIndex=0;faceIndex<numFaces;faceIndex++)
        	{
        		{
                	fprintf(stderr,"[");

                	Far::ConstIndexArray cia = level.getFaceVertices(faceIndex);
                	for (Far::ConstIndexArray::const_iterator iter = cia.begin();iter != cia.end(); ++iter)
                	{
                    	fprintf(stderr,"%d ",*iter);
                	}
                	fprintf(stderr,"]\t:\t");
        		}

            	fprintf(stderr,"[");

            	int channel = 0;
            	Far::ConstIndexArray uv_cia = level.getFaceFVarValues(faceIndex, channel);
            	for (Far::ConstIndexArray::const_iterator iter = uv_cia.begin();iter != uv_cia.end(); ++iter)
            	{
                	fprintf(stderr,"%d ",*iter);
            	}

            	fprintf(stderr,"]\n");
        	}

    	}
    }
```

```
maxLevel = 0
numLevels = 1
level.getNumFaces() = 6
[0 2 3 1 ]	:	[0 1 2 3 ]
[4 6 7 5 ]	:	[4 5 6 7 ]
[6 3 2 7 ]	:	[8 9 10 11 ]
[5 0 1 4 ]	:	[12 13 14 15 ]
[5 7 2 0 ]	:	[16 17 18 19 ]
[1 3 6 4 ]	:	[20 21 22 23 ]
```

**Comment by barfowl** [comment]
Glad that will get you moving forward. A couple of notes on your code using the Far::TopologyRefiner...

It's documented somewhere (Doxygen?) that the Bfr::RefinerSurfaceFactory only considers the base level of its Far::TopologyRefiner, so you never have to inspect the number of levels, etc.

The bfr/tutorial_2_2 makes more use of the Far::TopologyRefiner than most other tutorials and does the following to inspect topology:

    218        Far::TopologyLevel const & baseLevel = meshTopology.GetLevel(0);

followed by similar queries, e.g. baseLevel.GetNumFaces(), GetFaceVertices(face), etc.

Note that this does not use Vtr::internal::Level -- please never make use of anything in the "internal" namespace as, like the name says, it is for internal use and may change at any time. We typically only use namespace "internal" when we want inline access to implementation details and so have to make the header available.

The Far tutorials illustrate correct public use of the TopologyRefiner and its levels, i.e. TopologyLevel, but a quick glance at the TopologyLevel methods should cover most needs.

**Comment by nyue** [comment]
Thank you @barfowl , I have since remove all use of internal stuff and have it working with public interfaces and methods.

Cheers

**Comment by barfowl** [comment]
Glad to hear -- closing this then, thanks.
