### ISSUE TITLE
OSD_REAL_CAST use with with implicit 1.0 compile error on Intel Mac mini (embedded Intel GPU)

### ISSUE THREAD

**Issue by wayne-arnold-adsk** [PixarAnimationStudios/OpenSubdiv#1285]
when compiling OSD kernel for Intel GPU on Intel Mac mini  getting compiler errors

`OpenCL Error: [CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: Build Program driver returned (10015)
OpenCL Error: OpenCL Warning : clBuildProgram failed: could not build program for 0x1024500 (Intel(R) UHD Graphics 630) (err:-2)
OpenCL Error: [CL_BUILD_ERROR] : OpenCL Build Error : Compiler build log:
<program source>:912:18: error: call to 'convert_float' is ambiguous
            S *= OSD_REAL_CAST(1.0 / 12.0);
                 ^~~~~~~~~~~~~
<program source>:97:27: note: expanded from macro 'OSD_REAL_CAST'
    #define OSD_REAL_CAST convert_float
                          ^~~~~~~~~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4251:16: note: candidate function
__CLFN_CONVERT(convert_float, float);
               ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:3988:56: note: expanded from macro '__CLFN_CONVERT'
#define __CLFN_CONVERT(name, rtype) rtype __OVERLOAD__ name( uchar a); \
                                                       ^
`

there are cases where implicit float:double conversions doesn't seem to be supported
#elif defined(OSD_PATCH_BASIS_OPENCL)

    #define OSD_FUNCTION_STORAGE_CLASS static
    #define OSD_DATA_STORAGE_CLASS
    #define OSD_REAL float
    #define OSD_REAL_CAST convert_float`

OpenSubdiv/opensubdiv/osd/patchBasisCommon.h
there is 1 place using suffix "f"
const OSD_REAL one6th = OSD_REAL_CAST(1.0f / 6.0f);
other places don't

looks suspicious
        if (totalOrder == 0) {
            S *= OSD_REAL_CAST(1.0 / 12.0);
        } else if (totalOrder == 1) {
            S *= OSD_REAL_CAST(1.0 / 6.0);
            } else {
                S *= OSD_REAL_CAST(1.0 / 2.0);

git diff .
diff --git a/opensubdiv/osd/patchBasisCommon.h b/opensubdiv/osd/patchBasisCommon.h
index e65f742d..64ca4939 100644
--- a/opensubdiv/osd/patchBasisCommon.h
+++ b/opensubdiv/osd/patchBasisCommon.h
@@ -542,7 +542,7 @@ Osd_EvalBasisLinearTri(OSD_REAL s, OSD_REAL t,
 
         int totalOrder = ds + dt;
         if (totalOrder == 0) {
-            S *= OSD_REAL_CAST(1.0 / 12.0);
+            S *= OSD_REAL_CAST(1.0f / 12.0f);
 
             w[0]  = S * (1 - 2*M[1] - 4*M[2]          + 6*M[4] + 6*M[5] + 2*M[6]          - 6*M[8] - 4*M[9] -   M[10] - 2*M[11] + 2*M[13] +   M[14]);
             w[1]  = S * (1 + 2*M[1] - 2*M[2]          - 6*M[4]          - 4*M[6]          + 6*M[8] + 2*M[9] + 2*M[10] + 4*M[11] - 2*M[13] -   M[14]);
@@ -557,7 +557,7 @@ Osd_EvalBasisLinearTri(OSD_REAL s, OSD_REAL t,
             w[10] = S * (                                                                            2*M[9]                     - 2*M[13] -   M[14]);
             w[11] = S * (                                                                                                         2*M[13] +   M[14]);
         } else if (totalOrder == 1) {
-            S *= OSD_REAL_CAST(1.0 / 6.0);
+            S *= OSD_REAL_CAST(1.0f / 6.0f);
 
             if (ds != 0) {
                 w[0]  = S * (-1          + 3*M[2] + 3*M[3]          - 3*M[5] - 2*M[6] - 3*M[7] +   M[9]);
@@ -614,7 +614,7 @@ Osd_EvalBasisLinearTri(OSD_REAL s, OSD_REAL t,
                 w[10] = S * (                M[2] -   M[4] -   M[5]);
                 w[11] = S * (                         M[4] +   M[5]);
             } else {
-                S *= OSD_REAL_CAST(1.0 / 2.0);
+                S *= OSD_REAL_CAST(1.0f / 2.0f);
 
                 w[0]  = S * ( 1          - 2*M[2] -   M[3] +   M[5]);
                 w[1]  = S * (-1          + 2*M[2] + 2*M[3] -   M[5]);

appears to fix the compiler error.  
there are then warnings that appear

**Comment by davidgyu** [comment]
Filed as internal issue #OSD-397
