### ISSUE TITLE
Incorrectly duplicated code

### ISSUE THREAD

**Issue by ikolev21** [PixarAnimationStudios/OpenSubdiv#1311]
In `src/SeExpr2/UI/ExprCurve.cpp` , `ExprCurve::openDetail()`, lines 432-439 are verbatim copy of lines 423-430.

This looks like a copy-paste bug, I don't see any reason why the block of code within `if (dialog->exec() == QDialog::Accepted)` should be repeated twice.

**Comment by ikolev21** [comment]
Sorry, wrong repo, this was for SeExpr

**Comment by davidgyu** [comment]
We go ahead and delete this issue. Thanks!
