### ISSUE TITLE
[Question] Limit surface evaluation with OpenSubdiv 3.1.0 ?

### ISSUE THREAD

**Issue by mugulmd** [PixarAnimationStudios/OpenSubdiv#1341]
Hello,

I have a simple quad control mesh and I would like to evaluate the limit surface using a Catmull-Clark scheme.
From what I can read in the documentation, the `Bfr` module is *exactly* what I need, however the release notes states that this API has been introduced in OpenSubdiv **3.5.0**, and I'm stuck with OpenSubdiv **3.1.0** (due to internal studio constraints).

I couldn't find any documentation explaining how to perform limit surface evaluation without `Bfr`, but I'm guessing it's possible!
Could someone give me a quick explanation, or point me to some documentation that I might have missed ?
Thanks you!

**Comment by davidgyu** [comment]
Filed as internal issue: #OSD-448

**Comment by davidgyu** [comment]
Yes, it is possible to evaluate the limit surface using the `Far` API.

In the v3.1.0 release, take look at `tutorials/far/tutorial_6/far_tutorial_6.cpp`.

We've added some additional tutorials in recent releases, so you may also want to take a look in the current `dev` branch at `tutorials/far/tutorial_5_1/far_tutorial_5_1.cpp` and `tutorials/far/tutorial_5_2/far_tutorial_5_2.cpp`.
