### ISSUE TITLE
Infinite creases and watertight topology

### ISSUE THREAD

**Issue by rgirish28** [PixarAnimationStudios/OpenSubdiv#1347]
Hi,

I had a question about infinite creases and watertight topology for subdiv meshes. We were looking to implement a version of the watertight topology behaviour (shown in bfr_tutorial_2_2) within our renderer, but we found that it breaks all our regression tests implementing infinite creasing. Is this expected behaviour? 

I suppose infinitely sharpened creases cause discontinuities at the vertices and edges, so perhaps sharing the topology indexing isn't feasible for those cases? Or is it that the normals generated by the two faces sharing a creased edge must be different as currently we only compute one shading normal per shared vertex or edge points?

It is also possible that we haven't implemented the behaviour shown in tutorial_2_2 correctly but all our other regression tests pass showing the right topology. So please let us know whether this issue is unexpected and we can try to fix this. Thanks a lot!

Cheers,
Girish

EDIT: Sorry for raising the issue, but I have fixed this by changing the behaviour of normal computation to be one per face point rather than one per vertex, which gives me infinitely sharp edges and vertices. I'll close this issue as it is resolved. 

Happy New Year!

**Comment by rgirish28** [comment]
Resolved by change in computation of normals.

**Comment by davidgyu** [comment]
That sounds like a good solution.

There is a comment in that example source describing limitations of the implementation wrt non-manifold edges, but we might want to add a note about this concern as well.

Thanks!
