### ISSUE TITLE
variable "varyings" is not defined in glslPatchRegular.glsl

### ISSUE THREAD

**Issue by shengfu** [PixarAnimationStudios/OpenSubdiv#141]
In file glslPatchRegular.glsl, line 76-79:

#if OSD_NUM_VARYINGS > 0
    for (int i = 0; i < OSD_NUM_VARYINGS; ++i)
        output.v.varyings[i] = varyings[i];
#endif

I can't find the definition of variable "varyings". Does anyone test OSD_NUM_VARYING is not zero?

Thanks

Sheng

**Comment by jcowles** [comment]
This code has changed vastly in 3.0 and appears to be handling this case.  Closing this out.
