### ISSUE TITLE
Incorrect Gregory patch around pentagon topology

### ISSUE THREAD

**Issue by manuelk** [PixarAnimationStudios/OpenSubdiv#177]
![bad_pentagon](https://f.cloud.github.com/assets/1672752/657248/5b6f5e44-d547-11e2-95d4-eaa564783c22.png)

Note : uniform subdivision also appears to be having some issues with this...
## Obj to reproduce:

# This file uses centimeters as units for non-parametric coordinates.
v -6.185497 0.000000 3.501332
v 6.521884 0.000000 3.501332
v 0.168194 10.202231 3.501332
v -6.185497 10.202231 -4.155105
v 6.521884 10.202231 -4.155105
v -6.185497 0.000000 -4.155105
v 6.521884 0.000000 -4.155105
vt 0.375000 0.000000
vt 0.625000 0.000000
vt 0.500000 0.250000
vt 0.375000 0.500000
vt 0.625000 0.500000
vt 0.375000 0.750000
vt 0.625000 0.750000
vt 0.375000 1.000000
vt 0.625000 1.000000
vt 0.875000 0.000000
vt 0.875000 0.250000
vt 0.125000 0.000000
vt 0.125000 0.250000
f 3/3/1 5/5/2 4/4/3
f 4/4/4 5/5/5 7/7/6 6/6/7
f 6/6/8 7/7/9 2/9/10 1/8/11
f 2/2/12 7/10/13 5/11/14 3/3/15
f 3/3/16 4/13/17 6/12/18 1/1/19 2/2/20

**Comment by jtran56** [comment]
Filed as internal issue #151680.
