### ISSUE TITLE
Facevarying Data & Evaluation in OSD

### ISSUE THREAD

**Issue by bdcline** [PixarAnimationStudios/OpenSubdiv#182]
Hello, 

I've recently picked up OpenSubdiv and am ramping up on the API/library. As an experiment and to better familiarize myself with the code I'm attempting to replace a back end evaluation of a CatmallClark subd surface with OpenSubdiv for an exiting app.

One item that became a bit of a speed bump is FaceVaring data, specifically ST / textures. Ideally this application requires:
 1) FaceVarying ST's - including evaluation via the prman facevaryinginterpolateboundary modes.  We use mode 3 by defualt.
 2) Partials of the ST's; with respect to parametric UV is fine since we can use dPduv partials to calculate dPdst
 3) Ideally evaluating the limit surface.  (Currently using: OsdCpuEvalLimitController::EvalLimitSample)

Is there a recommendation on how to procede with evaluating face varying ST's?

It seems HBR and FAR support face varying data - however, OSD evaluation is not as clear, especially it looks like the different prman fvar interpolation modes aren't currently supported (Issue #176) .  Another way would be to pass through the face id & parametric coordinates through OSD and try to use HBR/FAR to evaluate the ST's on the other side.

Additionally - would there be a way to evaluate d[ST]/d[uv], similar to the call: m_osdEvalCtx->BindVertexBuffers(idesc, m_vertexData, odesc, m_Q, m_dQdu, m_dQdv)?  Or would falling back to a discrete sample-based approach be required?  Currently I'm using a discrete method - but ideally we'd like to move away from that given issues at Extraordinary Vertices. 

Thanks,
Bryan

P.S. Overall, very excited with what's in OpenSubdiv - Thanks for opensourcing it!

**Comment by davidgyu** [comment]
This should now be fully addressed in v3_2_0 including:
  - full support for face-varying interpolation modes
  - stencil tables and patch tables for face-varying data
  - limit stencil and patch evaluation for face-varying data w/ derivatives
  - example implementation of Analytic Displacement Mapping using Ptex
