### ISSUE TITLE
Navigation bar refresh bug

### ISSUE THREAD

**Issue by manuelk** [PixarAnimationStudios/OpenSubdiv#190]
repro:
- click on the "Subdivision Surfaces" link
- click on the "Introduction" link

![doc_bug](https://f.cloud.github.com/assets/1672752/764726/afb6bdb6-e817-11e2-9a29-37d71e3d0154.png)

**Comment by davidgyu** [comment]
We haven't seen this lately with any of the current browser builds: Chrome, Safari, Edge, Firefox, etc. on several platforms: LInux, Windows, macOS, iOS, Android, etc.
