### ISSUE TITLE
osdPolySmooth maya plugin under createSmoothMesh_objectGroups() does not properly handle non-quad mappings

### ISSUE THREAD

**Issue by scotbrew** [PixarAnimationStudios/OpenSubdiv#245]
The pow(4, level) is being used to determine the mapping between the base and smoothed mesh.  This is valid for quads, but not for non-quads.  The correct mapping needs to do: 
    level1 faces * pow(4, level-1).

**Comment by davidgyu** [comment]
The mayaPolySmooth (previously osdPolySmooth) plugin has been removed now that OpenSubdiv is integrated directly into maya. Thanks scotbrew for all of the good work to make that happen!
