### ISSUE TITLE
Osd Compute controllers need the ability to selectively work on primvars in a vertex buffer.

### ISSUE THREAD

**Issue by manuelk** [PixarAnimationStudios/OpenSubdiv#252]
Currently, a ComputeController interpolates systematically all elements in a vertex or varying buffer: the Refine functions need optional offsets / lengths to make it possible to interleave data in a vertex buffer from another source.

**Comment by davidgyu** [comment]
This has been addressed in OpenSubdiv 3.x by introducing the Osd::*Evaluator API. This replaces the previous Osd ComputeController interfaces with a more general API that can be used for refining primvar data and for evaluating limit-surface vertex, varying, and face-varying data.
