### ISSUE TITLE
[feature request] Direct ray-subd intersection

### ISSUE THREAD

**Issue by syoyo** [PixarAnimationStudios/OpenSubdiv#262]
+1. 

https://groups.google.com/forum/#!topic/opensubdiv/Ru5sHZD0gGo

It would be great if OpenSubdiv have efficient direct ray-patch intersector with spatial accelerator(e.g. BVH).

Efficient ray - patch intersector will be applicable for texturing purpose also: e.g. ptex texture painting on non-OpenGL environment.

**Comment by raw915** [comment]
What is the status of this? I know how to use Newton-Raphson iteration to solve for the central location point between two near or intersecting convex hull surfaces represented by bicubic B-splines. But the bookkeeping becomes overwhelming when the point is near an extraordinary vertex and subdivision is required. It appears that bookkeeping issues have been resolved in OpenSubdiv, so it would be good to have an API attached to OpenSubdiv to accomplish something like this.

blackencino said, "There's a bicubic intersection routine (of sorts) in Emld at Pixar (the
open-source part, so I'm allowed to talk about it). It is indeed an
iterative solver that uses Newton-Raphson before giving up and doing
recursive catmull-clark, but it gets the job done. Even if it's a
fallback, it would not be bad to have it in OpenSubd, no?

I can point you towards the code, if you're interested."

What is Emld? I can't find any references to it. Can someone point me towards the code if it exists?
