### ISSUE TITLE
SourceConfigType ownership within EffectDrawRegistry

### ISSUE THREAD

**Issue by gelder** [PixarAnimationStudios/OpenSubdiv#301]
From Sergey:

https://github.com/PixarAnimationStudios/OpenSubdiv/pull/300

One more little thing: it seems to be something wrong happening with ownership of SourceConfigType in EffectDrawRegistry from the examples application. I didn't see where sconfig is being freed and valgrind showed me memory leak when using the same registry in blender. So i ended up deleting sconfig once config is created in EffectDrawRegistry::_CreateDrawConfig().

Unfortunately, valgrind shows nothing in the example application (could be something to do with optimization flags, or it simply being confused by GPU usage or so) so can't tell for sure leak happens in examples.

Wouldn't mind having your guys check on ownership of this thing in OpenSubdiv.

**Comment by davidgyu** [comment]
We removed the DrawRegistry in the 3.0.0 release. Management of compiled shaders and shader source aggregation is now a client responsibility. The example viewers show one way to do this using the shader cache code in examples/common. Thanks!
