### ISSUE TITLE
Gregory patches & valence

### ISSUE THREAD

**Issue by manuelk** [PixarAnimationStudios/OpenSubdiv#315]
We are running into 2 problems w/ gregory patches:
1. vertex valence is currently limited on the CPU side by a static table of constants: we would like this table extended to support higher valences
2. vertices of valence 2 are currently not supported because of a `ef[valence-3]` lookup

Repro geo:

```
v -0.500000 -0.000000 0.500000
v 0.000000 -0.000000 0.500000
v 0.500000 -0.000000 0.500000
v 0.000000 0.000000 0.000000
v -0.500000 0.000000 -0.500000
v 0.000000 0.000000 -0.500000
v 0.500000 0.000000 -0.500000
f 2 1 5 6 4
f 2 4 6 7 3
```

**Comment by davidgyu** [comment]
Fixed in OpenSubdiv 3.x
