### ISSUE TITLE
Do not compile on fedora core 20... glfw error

### ISSUE THREAD

**Issue by Doudou3D** [PixarAnimationStudios/OpenSubdiv#371]
OS - Fedora core 20 64-bit
glfw-3.0.4 , glew-1.11.0-1

When i try to compile opensubdiv, i have some error messages : 

Linking CXX executable ../../bin/glPaintTest
Linking CXX executable ../../bin/glEvalLimit
Linking CXX executable ../../bin/glShareTopology
/usr/local/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x16ac): undefined reference to `XIQueryVersion'
/usr/local/lib/libglfw3.a(x11_window.c.o): In function `createWindow':
x11_window.c:(.text+0x679): undefined reference to `XISelectEvents'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/glPaintTest] Error 1
make[1]: *** [examples/glPaintTest/CMakeFiles/glPaintTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x16ac): undefined reference to `XIQueryVersion'
/usr/local/lib/libglfw3.a(x11_window.c.o): In function `createWindow':
x11_window.c:(.text+0x679): undefined reference to `XISelectEvents'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/glEvalLimit] Error 1
make[1]: *** [examples/glEvalLimit/CMakeFiles/glEvalLimit.dir/all] Error 2
/usr/local/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x16ac): undefined reference to `XIQueryVersion'
/usr/local/lib/libglfw3.a(x11_window.c.o): In function `createWindow':
x11_window.c:(.text+0x679): undefined reference to `XISelectEvents'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/glShareTopology] Error 1
make[1]: *** [examples/glShareTopology/CMakeFiles/glShareTopology.dir/all] Error 2
Linking CXX executable ../../bin/glFVarViewer
/usr/local/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x16ac): undefined reference to `XIQueryVersion'
/usr/local/lib/libglfw3.a(x11_window.c.o): In function `createWindow':
x11_window.c:(.text+0x679): undefined reference to `XISelectEvents'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/glFVarViewer] Error 1
make[1]: *** [examples/glFVarViewer/CMakeFiles/glFVarViewer.dir/all] Error 2
Linking CXX executable ../../bin/glPtexViewer
Linking CXX executable ../../bin/glViewer
/usr/local/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x16ac): undefined reference to `XIQueryVersion'
/usr/local/lib/libglfw3.a(x11_window.c.o): In function `createWindow':
x11_window.c:(.text+0x679): undefined reference to `XISelectEvents'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/glPtexViewer] Error 1
make[1]: *** [examples/glPtexViewer/CMakeFiles/glPtexViewer.dir/all] Error 2
/usr/local/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x16ac): undefined reference to `XIQueryVersion'
/usr/local/lib/libglfw3.a(x11_window.c.o): In function `createWindow':
x11_window.c:(.text+0x679): undefined reference to `XISelectEvents'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/glViewer] Error 1
make[1]: *** [examples/glViewer/CMakeFiles/glViewer.dir/all] Error 2
make: *** [all] Error 2

**Comment by manuelk** [comment]
IIRC, a relatively recent update to GLFW introduced a dependency to lib Xi, which has been reflected in our FindGLFW.cmake with this change: 7ac73157f4a88cd5f417682415bd1cdc794f7721

This is currently in the dev branch but should be rolled shortly into the master branch with the upcoming 3.0.0 Beta release (hoping by end of week)

**Comment by Doudou3D** [comment]
Thx i work now very fine. ;-)

**Comment by manuelk** [comment]
Excellent - closing this as resolved then.
