### ISSUE TITLE
GLSL compute crash

### ISSUE THREAD

**Issue by hsdk** [PixarAnimationStudios/OpenSubdiv#377]
The glsl compute stencil evaluator is crashing, e.g. when switching to this evaluator in the glViewer.
Tested GPUs: GTX 780, 560, Radeon 7290, latest release drivers on Windows.

The crash is caused by: 
1. The compute shader not being compiled since the buffer bindings are not found at link time when using the dynamic entry point to computeStencil.
2. The stencilSizes buffer is a ubyte buffer. The current implementation uses unsigned char as data type but this type is not known glsl, or am i missing an extension? After changing the type to uint the buffer is not intepreted correctly. 

Here is a workaround https://github.com/hsdk/OpenSubdiv/commit/d589ff3435f72ff907ca4b7bfedc5c363331c4d7 but i'm not yet satisfied with the solution since i had to removed the dynamic entry point and convert the stencil sizes over to an uint array before creating the glsl stencil table buffers. Any suggestions to convince gl to interpet the ubyte buffer correctly in the compute shader?

**Comment by manuelk** [comment]
I am not sure this problem is hardware related - more likely driver, GL or GLEW... Oddly enough, the GLSL stencil compute kernels are the ones that have given me the least amount of trouble (GTX 980, GTX 680m, HD7900, Q4000, Q5000, K4000...). Can't say the same for CUDA / CL... although some of my problems may be related to your findings.

**Comment by significant-bit** [comment]
Pretty sure this has been resolved. I'm able to run OSD 3.0.3's GLSL Compute on a recent AMD A10 (forget the model number) and Intel HD 4600. Also Blender 2.76 (using OSD 3.0.0) on nVidia GTX 970. All of these on Windows 10.

**Comment by davidgyu** [comment]
Yes, we changed the Osd Evaluator API significantly for the 3.x releases including improving the strategy for caching compiled programs and making the implementation much more consistent for evaluating stencils, patches, w/ and w/o derivatives, etc. The current implementation has been tested widely on NVIDIA, AMD, Intel GPUs and Windows, Linux, macOS, etc.
