### ISSUE TITLE
Are header files self contained ?

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#382]
Hi,

  Are some header files not meant to be include ? If not, are header files self contained i.e. it will include things it requires rather than assume an include hierarchy of a specific order before they are included ?

  I encountered this on OS X Clang++ 6.1 but I recall earlier tests (don't have access at the moment) on CentOS is fine.

--main.cpp
#include <hbr/vertexEdit.h>

int main()
{
    return 0;
}
--main.cpp

Scanning dependencies of target test_hbrVertexEdit_header
[100%] Building CXX object dev/CMakeFiles/test_hbrVertexEdit_header.dir/test_hbrVertexEdit_header.cpp.o
In file included from /Users/nicholas/projects/OSDLSE/OpenSubdivLimitSurfaceEvaluator_git/dev/test_hbrVertexEdit_header.cpp:1:
In file included from /Users/nicholas/systems/OpenSubdiv/v3_0_0_beta/include/opensubdiv/hbr/vertexEdit.h:29:
In file included from /Users/nicholas/systems/OpenSubdiv/v3_0_0_beta/include/opensubdiv/hbr/../hbr/hierarchicalEdit.h:131:
In file included from /Users/nicholas/systems/OpenSubdiv/v3_0_0_beta/include/opensubdiv/hbr/../hbr/face.h:35:
/Users/nicholas/systems/OpenSubdiv/v3_0_0_beta/include/opensubdiv/hbr/../hbr/fvarData.h:181:22: error: 
      no template named 'HbrVertexEdit'; did you mean 'HbrVertex'?
                case HbrVertexEdit<T>::Set:
                     ^~~~~~~~~~~~~
                     HbrVertex

Cheers

**Comment by manuelk** [comment]
I am pretty sure that HbrVertexEdit::Set is correct - however what may be happening here might be related to the OpenSubdiv namespace shenanigans. If you have a reasonably easy repro-case that you can share, i can take a look at it. However, we are deprecating Hbr, so i won't be able to spend too much time and might not follow through with a patch...

**Comment by c64kernal** [comment]
Hbr is now deprecated in 3.0.  Please open a new issue if you can repro in the 3.0 headers.
