### ISSUE TITLE
include path convention/consistency

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#383]
Hi,
        Looking at examples like glEvalLimit.cpp, I see the following
```
#include <osd/cpuComputeContext.h>
```
        The CMake installation/packaging of headers for OpenSubdiv for both v2 and v3 adds a "opensubdiv" parent directory

         I believe the convention is either to have the following
```
#include <opensubdiv/osd/cpuComputeContext.h>
```
        or move all the subdirectory up one level and do away with the (IMHO) superfluous "opensubdiv" parent directory.

Cheers

**Comment by manuelk** [comment]
Our code "examples" are not always sterling representatives of best practices - glEvalLimit & friends should be using :
```
#include <opensubdiv/osd/cpuComputeContext.h>
```
I'll put this fix on the back-burner for now though.

**Comment by davidgyu** [comment]
Closing this since #767 covers this issue and more. Thanks!
