### ISSUE TITLE
hbr deprecation advice

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#387]
Hi,

  I am porting some old 2.x code which uses the HbrFace class

  Here the relevant snippet of how I get the u,v via the GetFVarData() call

  What is the current way to access a vertex UV at the ptex face level ? Which tutorial example would be relevant as a reference starting point ?

```
	typedef OpenSubdiv::HbrMesh<Vertex>      Hmesh;
	typedef OpenSubdiv::HbrFace<Vertex>      Hface;
	typedef OpenSubdiv::HbrVertex<Vertex>    Hvertex;
	typedef OpenSubdiv::HbrHalfedge<Vertex>  Hhalfedge;
```
```
		Hface *face = hmesh->GetFace( faceIndex );
		assert(face);
		bool faceIsExtraordinary = hmesh->GetSubdivision()->FaceIsExtraordinary(hmesh, face);
		int faceDepth = face->GetDepth();
		int ptex_index = face->GetPtexIndex();
		// We only accumulate information from non-Extraordinary faces AND depth==1 (refined)
		printf("buildFace2PtexTableFromHmesh() faceIsExtraordinary = \"%s\" faceIndex = %d ptex_index = %d faceDepth = %d depth_of_interest = %d\n",
				(faceIsExtraordinary?"true":"false"),faceIndex,ptex_index,faceDepth,depth_of_interest);
		if (!faceIsExtraordinary && faceDepth==depth_of_interest)
		{
			printf("buildFace2PtexTableFromHmesh() ptex_index = %d\n",ptex_index);
			bool ptex_index_found = o_f2pinfo.ptexuvs_map.find(ptex_index)!=o_f2pinfo.ptexuvs_map.end();
			if (!ptex_index_found)
			{
				int numFaceVertices = face->GetNumVertices();
				if (numFaceVertices != 4)
				{
					LOG(ERROR) << "Non-quad after Hbr refinement";
					throw std::runtime_error("Non-quad after Hbr refinement");
				}
				UVsContainer ptex_uvs;
				for (int faceVerticesIndex=0;faceVerticesIndex<numFaceVertices;faceVerticesIndex++)
				{
					float *uValue = face->GetFVarData(faceVerticesIndex).GetData(0);
					float *vValue = face->GetFVarData(faceVerticesIndex).GetData(1);
```
Cheers

**Comment by manuelk** [comment]
I believe this is what you are looking for:
http://graphics.pixar.com/opensubdiv/docs/far_tutorial_3.html

**Comment by nyue** [comment]
Thanks Manuel.

I compiled the example and ran the code and visualize the UVs.

The UVs are "smoothed" out, I was expect the corners to be sharp and thereby retaining the original UVs. To me these UV will not match the original placement of textures.

![facevaryinguvs](https://cloud.githubusercontent.com/assets/486172/5929815/ad8eb8ba-a63c-11e4-8f79-83bc5cc23ea1.png)

**Comment by nyue** [comment]
Found the reason. For my use case, I need to change to this

    options.SetFVarLinearInterpolation(Sdc::Options::FVAR_LINEAR_BOUNDARIES);

**Comment by manuelk** [comment]
This is indeed the correct solution. Documentation here:

http://internal-graphics.pixar.com/opensubdiv/docs/subdivision_surfaces.html#face-varying-interpolation-rules

Ok to close this ?

**Comment by nyue** [comment]
Yes, please close. Thank you.
