### ISSUE TITLE
GLFW_LOCATION doesn't seem to work on OSX

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/OpenSubdiv#388]
The docs claim -DGLFW_LOCATION should direct CMake to the correct version of GLFW, however I had to use GLFW_INCLUDE_DIR to get it to work.

I have a system version of glfw in /usr/local/include (2.x) and another version that I was trying to explicitly use stored locally in my OpenSubdiv build directory. CMake would only find the 2.x glfw version until I used GLFW_INCLUDE_DIR.

**Comment by jcowles** [comment]
Additionally, I had to specify:
-DGLFW_glfw_LIBRARY=glfw-3.1/lib/libglfw.dylib

Which seems like an internal variable...

**Comment by manuelk** [comment]
This should work just from GLFW_LOCATION, but i haven't tested that build in a while - can you paste the values you used for your overrides ? I'll take a look at the suffixes in the search path tomorrow.

**Comment by jcowles** [comment]
I have my build setup in 
OpenSubdiv.dev/_build

glfw is built out (and installed) to:
OpenSubdiv.dev/_build/glfw3.1/{include,lib}

from _build, I'm running:
cmake -DGLFW_LOCATION=glfw-3.1/ ..

**Comment by hsdk** [comment]
Using the absolute path should work but i cannot test this right now.

**Comment by jcowles** [comment]
I did also try using an absolute path.

--
Jeremy

**Comment by manuelk** [comment]
Absolute path should work - i'll see if i can repro this on my MBP over the week-end.

**Comment by manuelk** [comment]
Tested on 2 different OS X machines and neither had a problem detecting GLFW with a full path - could you paste both your config script and the CMake spewage please ?

**Comment by jcowles** [comment]
Thanks for testing - Did you happen to try with another version of glfw installed to a standard location?

--
Jeremy

**Comment by jcowles** [comment]
Relevant spewage is:
-- Could NOT find GLFW: Found unsuitable version "2.7.7", but required is at least "3.0.0" (found /usr/local/include)

Here is everything:

rm CMakeCache.txt
pwd
/Users/jcowles/Documents/github/OpenSubdiv.dev/_build

cmake -DGLFW_LOCATION=/Users/jcowles/Documents/github/OpenSubdiv.dev/_build/glfw-3.1 ..
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Compiling OpenSubdiv version v3_0_0_beta
-- Using cmake version 2.8.9
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Could NOT find TBB (missing:  TBB_INCLUDE_DIR TBB_LIBRARIES) (Required is at least version "4.0")
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework  
-- Could NOT find CLEW (missing:  CLEW_INCLUDE_DIR CLEW_LIBRARY) 
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (Required is at least version "1.1") 
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "4.0")
-- Could NOT find GLFW: Found unsuitable version "2.7.7", but required is at least "3.0.0" (found /usr/local/include)
-- Could NOT find PTex (missing:  PTEX_INCLUDE_DIR PTEX_LIBRARY) (Required is at least version "2.0")
-- Found GLEW: /usr/include  
-- Found Maya: /Applications/Autodesk/maya2012/Maya.app/Contents/MacOS/maya (found suitable version "201200", required is "201200") 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) (Required is at least version "1.8.4")
-- Could NOT find Docutils (missing:  RST2HTML_EXECUTABLE) (Required is at least version "0.6")
CMake Warning at CMakeLists.txt:378 (message):
  OpenMP was not found : support for OMP parallel compute kernels will be
  disabled in Osd.  If your compiler supports OpenMP directives, please refer
  to the FindOpenMP.cmake shared module in your cmake installation.


CMake Warning at CMakeLists.txt:394 (message):
  TBB was not found : support for TBB parallel compute kernels will be
  disabled in Osd.  If your compiler supports TBB directives, please refer to
  the FindTBB.cmake shared module in your cmake installation.


CMake Warning at CMakeLists.txt:459 (message):
  OpenCL was found, but CLEW was not.  Building with OpenCL support enabled,
  but the built binary will not be portable to systems without OpenCL
  installed.


CMake Warning at CMakeLists.txt:480 (message):
  CUDA was not found : support for CUDA parallel compute kernels will be
  disabled in Osd.  If you have the CUDA SDK installed, please refer to the
  FindCUDA.cmake shared module in your cmake installation.


CMake Warning at CMakeLists.txt:493 (message):
  Ptex was not found : the OpenSubdiv Ptex example will not be available.  If
  you do have Ptex installed and see this message, please add your Ptex path
  to FindPTex.cmake in /Users/jcowles/Documents/github/OpenSubdiv.dev/cmake
  or set it through the PTEX_LOCATION cmake command line argument or
  environment variable.


CMake Warning at regression/CMakeLists.txt:52 (message):
  The following libraries could not be found : glfw.  The osd regression test
  will not be available.  If you have these libraries installed, please
  specify their path to cmake (through the GLEW_LOCATION and GLFW_LOCATION
  command line arguments or environment variables).


-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
-- Found PNG: /opt/local/lib/libpng.dylib (found version "1.4.8") 
CMake Warning at examples/CMakeLists.txt:74 (message):
  The following libraries could not be found : glfw.  The glViewer and
  ptexViewer examples will not be available.  If you have these libraries
  installed, please specify their path to cmake (through the GLEW_LOCATION
  and GLFW_LOCATION command line arguments or environment variables).


CMake Warning at documentation/CMakeLists.txt:52 (message):
  Doxyen was not found : support for Doxygen automated API documentation is
  disabled.


-- Found PythonInterp: /opt/local/bin/python2.6 (found suitable version "2.6.7", required is "2.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jcowles/Documents/github/OpenSubdiv.dev/_build

**Comment by jcowles** [comment]
Oh, the problem is the call to find_path -- it always prefers system paths first, and it's only returning one result. So in my case, /usr/local always wins.

Also, I noticed the {CUSTOMPACKAGE}_LOCATION variables are stored as "options" which means they are booleans to CMake, but they should be stored as PATH variables. 

I think I have a fix for both issues.

**Comment by jcowles** [comment]
My fix for the first issue currently involves calling find_path twice, but that seems hacky and still error prone, do you know the correct way to do the following?

# XXX
# First, probe the GLFW_LOCATION, before other paths.
# This ensures GLFW_LOCATION is the strongest location, when multiple GLFW paths exist.
find_path( GLFW_INCLUDE_DIR 
    NAMES
        GL/glfw.h
        GLFW/glfw3.h
    PATHS
        "${GLFW_LOCATION}/include"
        "$ENV{GLFW_LOCATION}/include"
    DOC 
        "The directory where GL/glfw.h resides"
    NO_DEFAULT_PATH
)

# Probe other paths.
find_path( GLFW_INCLUDE_DIR 
    NAMES
        GL/glfw.h
        GLFW/glfw3.h
    PATHS
        "$ENV{PROGRAMFILES}/GLFW/include"
        "${OPENGL_INCLUDE_DIR}"
        /usr/openwin/share/include
        /usr/openwin/include
        /usr/X11R6/include
        /usr/include/X11
        /opt/graphics/OpenGL/include
        /opt/graphics/OpenGL/contrib/libglfw
        /usr/include/GL
        /usr/include
    DOC 
        "The directory where GL/glfw.h resides"
)

**Comment by jcowles** [comment]
This is an option maybe worth stating in the docs:

https://blogs.kde.org/2008/12/12/how-get-cmake-find-what-you-want-it

Basically, when you have multiple libs installed, you can set CMAKE_PREFIX_PATH as a first priority override.

**Comment by manuelk** [comment]
This doesn't seem right : AFAIK, find_path does not go for default system paths first, and there are other examples that would also fail on Linux (GLEW for instance). Assuming i am reading it correctly, the documentation (http://www.cmake.org/cmake/help/v3.0/command/find_path.html) would agree with me on this.

Ultimately, you can run cmake through strace to see what is been searched in what order and validate your hypothesis (i think there is a variable to get this out of cmake, but i can't remember what it is)

Few thoughts:
- after being bit a few times, i now blow the entire build directory, not just the CMakeCache.txt file...
- since we tend to build with individual dependency overrides, PREFIX_PATH is probably not something we want to recommend using
- your path to GLFW is to the top of that directory : does glfw have its own internal build / inst directory ? because if it does, that's where you need to point CMake at...

From experience, it is usually more likely that something does not line up between your config script and the paths CMake is scanning than the GLFW_LOCATION override not working. If your machine is portable, bring it in and i'll take a look at it.

**Comment by manuelk** [comment]
Brought out the artillery : strace actually confirms your hypothesis and i was incorrect. CMake does indeed give precendence to $PATH (%PATH%) and $INCLUDE before localization.

Trying NO_SYSTEM_ENVIRONMENT_PATH might work, since most of our Find modules search typical system paths after location overrides. This search order is very backward and i am surprised that i haven't run into this problem with libraries like GLEW, of which i often have both a system version and recent build...

**Comment by jcowles** [comment]
Yes, from the docs, rules 4 and 5 indicate sys paths will be searched *before* PATHS, rule 6

Maybe HINTS is where we should be placing GLFW_LOCATION, instead of PATHS

--
Jeremy
