### ISSUE TITLE
glStencilViewer aborts on catmark_fan

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/OpenSubdiv#390]
Here is the output:

./bin/glStencilViewer

(select catmark_fan shape)

Assertion failed: (pEdgeFaces.size() == 2), function populateChildValuesForEdgeVertex, file /Users/jcowles/Documents/github/OpenSubdiv.dev/opensubdiv/vtr/fvarRefinement.cpp, line 188.
Abort trap: 6

It may not matter, but I'm running on OSX 10.10

**Comment by jcowles** [comment]
I'm running in debug mode and we're hitting this assert (in vtr/fvarRefinement.cpp):

    inline int
    FVarRefinement::populateChildValuesForEdgeVertex(Index cVert, Index pEdge) {
    
        //  If we have a boundary edge with a mismatched end vertex, we only have one
        //  value and such cases were already initialized on construction, so return:
        //
        ConstIndexArray  pEdgeFaces = _parentLevel.getEdgeFaces(pEdge);
    
        if (pEdgeFaces.size() == 1) return 1;
        assert(pEdgeFaces.size() == 2);

**Comment by manuelk** [comment]
It's a known issue - non-manifold is not fully implemented yet (barfowl is hoping to have a fix soon). We still have to formulate smooth interpolation rules for non-manifold as well.

**Comment by jcowles** [comment]
Ah ok

**Comment by barfowl** [comment]
Right -- this is a non-manifold *face-varying* issue, which still has a few
holes to be plugged...

- barry

**Comment by barfowl** [comment]
This was addressed long ago when face-varying refinement was extended to better handle non-manifold regions.  The assert() here no longer exists.  Please re-open if necessary, thanks.
