### ISSUE TITLE
static varible in far/patchDescriptor.cpp caused data race issue 

### ISSUE THREAD

**Issue by shengfuintel** [PixarAnimationStudios/OpenSubdiv#394]
There are two static variables in far/patchDescriptor.cpp. If multi OSD meshes are generated in parallel, these variables run into data race issue. It crashed in my application. It need a mutex to protect the initiation.

**Comment by manuelk** [comment]
Indeed - this is a problem : thanks for bringing it up.

However, we currently have no access to a mutex in far (TBB or C++11 are currently not viable options). The best path forward here will be to replace the existing initialization code with a static assignment. Let me see if i can hammer something out quickly...

**Comment by manuelk** [comment]
This should fix the data race problem - thanks for submitting this bug.

**Comment by shengfuintel** [comment]
Thanks for the quick fix.

**Comment by manuelk** [comment]
Most welcome
