### ISSUE TITLE
maximum valence for a triangle face is incorrect

### ISSUE THREAD

**Issue by shengfuintel** [PixarAnimationStudios/OpenSubdiv#395]
In OSD3, the maximum valence for a triangle face (a whole mesh only has one triangle, no other faces) is 3. It should be 4 if it subdivided twice. The code in PatchTablesFactory::createAdaptive and createUniform only looks into the maximum valence in level 0. I think it is safe to set maximum valence to 4 as minimum value.

**Comment by shengfuintel** [comment]
It caused crashed in Gregory patch evaluation code.

**Comment by manuelk** [comment]
I vaguely remember already fixing this very problem in the 2.x PatchTables /sigh

Please go ahead and submit a pull request (dev branch) for a fix if you have one.

**Comment by barfowl** [comment]
This was fixed long ago in 3.0.  Please reopen if that turns out not to be the case.  Thanks
