### ISSUE TITLE
VtrViewer: disabling adaptive results in GL error, segfault

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/OpenSubdiv#431]
Running on OSX 10.10.2, early 2011 w/AMD GPU -- @davidgyu I sync'd back before the recent shader refactoring and it still crashes, so it seems unrelated.

**Comment by davidgyu** [comment]
Yes, this has been broken for quite a while and is something I've been meaning to look into. Good to have a bug to track this!

**Comment by jcowles** [comment]
Is this still broken?

**Comment by jcowles** [comment]
Actually, I just confirmed, it is not!
