### ISSUE TITLE
undefined reference to `XineramaQueryScreens' while building the examples

### ISSUE THREAD

**Issue by opeca64** [PixarAnimationStudios/OpenSubdiv#473]
Hit a simple bug inside of the examples.  I believe this is Ubuntu-specific. ( I have turned off <code>CLEW</code> because of mentioned bug in #472 )

<pre><code>
MYUSERNAME@MYCOMPUER:/home/pion/ext/openSubdiv-current/build$ make
[  0%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuKernel.cpp.o
[  1%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuComputeController.cpp.o
[  1%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuComputeContext.cpp.o
[  1%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuEvalLimitContext.cpp.o
[  2%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuEvalLimitController.cpp.o
[  2%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuEvalLimitKernel.cpp.o
[  2%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuEvalStencilsContext.cpp.o
[  3%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuEvalStencilsController.cpp.o
[  3%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuSmoothNormalContext.cpp.o
[  4%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuSmoothNormalController.cpp.o
[  4%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/cpuVertexBuffer.cpp.o
[  4%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/drawContext.cpp.o
[  5%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/drawRegistry.cpp.o
[  5%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/evalLimitContext.cpp.o
[  5%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/ptexTextureLoader.cpp.o
[  6%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/ptexMipmapTextureLoader.cpp.o
[  6%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/ompKernel.cpp.o
[  6%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/ompComputeController.cpp.o
[  7%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/ompEvalStencilsController.cpp.o
[  7%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/ompSmoothNormalController.cpp.o
[  8%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/tbbKernel.cpp.o
[  8%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/tbbComputeController.cpp.o
[  8%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/tbbEvalStencilsController.cpp.o
[  9%] Building CXX object opensubdiv/osd/CMakeFiles/osd_cpu_obj.dir/tbbSmoothNormalController.cpp.o
[  9%] Built target osd_cpu_obj
[ 10%] Building CXX object opensubdiv/sdc/CMakeFiles/sdc_obj.dir/crease.cpp.o
[ 10%] Building CXX object opensubdiv/sdc/CMakeFiles/sdc_obj.dir/typeTraits.cpp.o
[ 10%] Built target sdc_obj
[ 11%] Building CXX object opensubdiv/vtr/CMakeFiles/vtr_obj.dir/fvarLevel.cpp.o
[ 11%] Building CXX object opensubdiv/vtr/CMakeFiles/vtr_obj.dir/fvarRefinement.cpp.o
[ 11%] Building CXX object opensubdiv/vtr/CMakeFiles/vtr_obj.dir/level.cpp.o
[ 12%] Building CXX object opensubdiv/vtr/CMakeFiles/vtr_obj.dir/quadRefinement.cpp.o
[ 12%] Building CXX object opensubdiv/vtr/CMakeFiles/vtr_obj.dir/refinement.cpp.o
[ 12%] Building CXX object opensubdiv/vtr/CMakeFiles/vtr_obj.dir/sparseSelector.cpp.o
[ 13%] Building CXX object opensubdiv/vtr/CMakeFiles/vtr_obj.dir/triRefinement.cpp.o
[ 13%] Built target vtr_obj
[ 13%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/error.cpp.o
[ 13%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/gregoryBasis.cpp.o
[ 14%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/patchDescriptor.cpp.o
[ 14%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/patchMap.cpp.o
[ 15%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/patchTables.cpp.o
[ 15%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/patchTablesFactory.cpp.o
[ 15%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/stencilTablesFactory.cpp.o
[ 16%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/topologyRefiner.cpp.o
[ 16%] Building CXX object opensubdiv/far/CMakeFiles/far_obj.dir/topologyRefinerFactory.cpp.o
[ 16%] Built target far_obj
[ 16%] Building CXX object opensubdiv/CMakeFiles/osd_dynamic_cpu.dir/version.cpp.o
Linking CXX shared library ../lib/libosdCPU.so
[ 16%] Built target osd_dynamic_cpu
[ 16%] Building CXX object opensubdiv/tools/stringify/CMakeFiles/stringify.dir/main.cpp.o
Linking CXX executable ../../../bin/stringify
[ 16%] Built target stringify
[ 16%] Generating clKernel.gen.h
[ 16%] Generating glslPatchCommon.gen.h
[ 17%] Generating glslPatchBSpline.gen.h
[ 17%] Generating glslPatchGregory.gen.h
[ 18%] Generating glslPatchTransition.gen.h
[ 18%] Generating glslPtexCommon.gen.h
[ 18%] Generating glslTransformFeedbackKernel.gen.h
[ 19%] Generating glslComputeKernel.gen.h
Scanning dependencies of target osd_gpu_obj
[ 19%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glPtexTexture.cpp.o
[ 20%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glPtexMipmapTexture.cpp.o
[ 20%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/cpuGLVertexBuffer.cpp.o
[ 20%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glDrawContext.cpp.o
[ 21%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glDrawRegistry.cpp.o
[ 21%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glVertexBuffer.cpp.o
[ 22%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glslTransformFeedbackComputeContext.cpp.o
[ 22%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glslTransformFeedbackComputeController.cpp.o
[ 22%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glslComputeContext.cpp.o
[ 23%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/glslComputeController.cpp.o
[ 23%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/clComputeContext.cpp.o
In file included from /usr/local/cuda/include/CL/opencl.h:44:0,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/../osd/opencl.h:34,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/clComputeContext.h:31,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/clComputeContext.cpp:27:
/usr/local/cuda/include/CL/cl_gl_ext.h:44:4: warning: "/*" within comment [-Wcomment]
  * /* cl_VEN_extname extension  */
 ^
[ 23%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/clComputeController.cpp.o
In file included from /usr/local/cuda/include/CL/opencl.h:44:0,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/../osd/../osd/opencl.h:34,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/../osd/clComputeContext.h:31,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/clComputeController.h:31,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/clComputeController.cpp:25:
/usr/local/cuda/include/CL/cl_gl_ext.h:44:4: warning: "/*" within comment [-Wcomment]
  * /* cl_VEN_extname extension  */
 ^
[ 24%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/clVertexBuffer.cpp.o
In file included from /usr/local/cuda/include/CL/opencl.h:44:0,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/../osd/opencl.h:34,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/clVertexBuffer.h:29,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/clVertexBuffer.cpp:26:
/usr/local/cuda/include/CL/cl_gl_ext.h:44:4: warning: "/*" within comment [-Wcomment]
  * /* cl_VEN_extname extension  */
 ^
[ 24%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/clGLVertexBuffer.cpp.o
In file included from /usr/local/cuda/include/CL/opencl.h:44:0,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/../osd/opencl.h:34,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/clGLVertexBuffer.h:31,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/clGLVertexBuffer.cpp:25:
/usr/local/cuda/include/CL/cl_gl_ext.h:44:4: warning: "/*" within comment [-Wcomment]
  * /* cl_VEN_extname extension  */
 ^
[ 24%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/cudaComputeController.cpp.o
[ 25%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/cudaComputeContext.cpp.o
[ 25%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/cudaVertexBuffer.cpp.o
[ 26%] Building CXX object opensubdiv/osd/CMakeFiles/osd_gpu_obj.dir/cudaGLVertexBuffer.cpp.o
[ 26%] Built target osd_gpu_obj
[ 27%] Building NVCC (Device) object opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/./osd_dynamic_gpu_generated_cudaKernel.cu.o
-- Removing /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/./osd_dynamic_gpu_generated_cudaKernel.cu.o
/usr/bin/cmake -E remove /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/./osd_dynamic_gpu_generated_cudaKernel.cu.o
-- Generating dependency file: /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.NVCC-depend
/usr/local/cuda/bin/nvcc -M -D__CUDACC__ /home/pion/ext/openSubdiv-current/opensubdiv/osd/cudaKernel.cu -o /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -DOPENSUBDIV_VERSION_STRING=\"3.0.0.beta\" -DOPENSUBDIV_HAS_OPENMP -DOPENSUBDIV_HAS_TBB -DGLFW_VERSION_3 -DOSD_USES_GLEW -DOPENSUBDIV_HAS_GLSL_TRANSFORM_FEEDBACK -DOPENSUBDIV_HAS_GLSL_COMPUTE -DOPENSUBDIV_HAS_OPENCL -DOPENSUBDIV_HAS_CUDA -DOPENSUBDIV_HAS_PTEX -DOPENSUBDIV_HAS_MAYA -Dosd_dynamic_gpu_EXPORTS -Xcompiler ,\"-fPIC\",\"-O3\",\"-DNDEBUG\" -Xcompiler -fPIC --gpu-architecture compute_20 --gpu-code sm_30 -DNVCC -I/usr/local/cuda/include -I/home/pion/ext/openSubdiv-current/opensubdiv -I/home/pion/ext/ptex-current/install/include -I/opt/intel/tbb/include -I/usr/include -I/usr/local/cuda/include -I/usr/include/nvidia-346/CL/c
-- Generating temporary cmake readable file: /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.depend.tmp
/usr/bin/cmake -D input_file:FILEPATH=/home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.NVCC-depend -D output_file:FILEPATH=/home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.depend.tmp -P /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake
-- Copy if different /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.depend.tmp to /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.depend
/usr/bin/cmake -E copy_if_different /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.depend.tmp /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.depend
-- Removing /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.depend.tmp and /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.NVCC-depend
/usr/bin/cmake -E remove /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.depend.tmp /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/osd_dynamic_gpu_generated_cudaKernel.cu.o.NVCC-depend
-- Generating /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/./osd_dynamic_gpu_generated_cudaKernel.cu.o
/usr/local/cuda/bin/nvcc /home/pion/ext/openSubdiv-current/opensubdiv/osd/cudaKernel.cu -c -o /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/./osd_dynamic_gpu_generated_cudaKernel.cu.o -ccbin /usr/bin/cc -m64 -DOPENSUBDIV_VERSION_STRING=\"3.0.0.beta\" -DOPENSUBDIV_HAS_OPENMP -DOPENSUBDIV_HAS_TBB -DGLFW_VERSION_3 -DOSD_USES_GLEW -DOPENSUBDIV_HAS_GLSL_TRANSFORM_FEEDBACK -DOPENSUBDIV_HAS_GLSL_COMPUTE -DOPENSUBDIV_HAS_OPENCL -DOPENSUBDIV_HAS_CUDA -DOPENSUBDIV_HAS_PTEX -DOPENSUBDIV_HAS_MAYA -Dosd_dynamic_gpu_EXPORTS -Xcompiler ,\"-fPIC\",\"-O3\",\"-DNDEBUG\" -Xcompiler -fPIC --gpu-architecture compute_20 --gpu-code sm_30 -DNVCC -I/usr/local/cuda/include -I/home/pion/ext/openSubdiv-current/opensubdiv -I/home/pion/ext/ptex-current/install/include -I/opt/intel/tbb/include -I/usr/include -I/usr/local/cuda/include -I/usr/include/nvidia-346/CL/c
/home/pion/ext/openSubdiv-current/opensubdiv/osd/cudaKernel.cu(223): warning: type qualifier is meaningless on cast type

/home/pion/ext/openSubdiv-current/opensubdiv/osd/cudaKernel.cu(223): warning: type qualifier is meaningless on cast type

Generated /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/./osd_dynamic_gpu_generated_cudaKernel.cu.o successfully.
[ 27%] Building NVCC (Device) object opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/./osd_static_gpu_generated_cudaKernel.cu.o
-- Removing /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/./osd_static_gpu_generated_cudaKernel.cu.o
/usr/bin/cmake -E remove /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/./osd_static_gpu_generated_cudaKernel.cu.o
-- Generating dependency file: /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.NVCC-depend
/usr/local/cuda/bin/nvcc -M -D__CUDACC__ /home/pion/ext/openSubdiv-current/opensubdiv/osd/cudaKernel.cu -o /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -DOPENSUBDIV_VERSION_STRING=\"3.0.0.beta\" -DOPENSUBDIV_HAS_OPENMP -DOPENSUBDIV_HAS_TBB -DGLFW_VERSION_3 -DOSD_USES_GLEW -DOPENSUBDIV_HAS_GLSL_TRANSFORM_FEEDBACK -DOPENSUBDIV_HAS_GLSL_COMPUTE -DOPENSUBDIV_HAS_OPENCL -DOPENSUBDIV_HAS_CUDA -DOPENSUBDIV_HAS_PTEX -DOPENSUBDIV_HAS_MAYA -Xcompiler ,\"-O3\",\"-DNDEBUG\" -Xcompiler -fPIC --gpu-architecture compute_20 --gpu-code sm_30 -DNVCC -I/usr/local/cuda/include -I/home/pion/ext/openSubdiv-current/opensubdiv -I/home/pion/ext/ptex-current/install/include -I/opt/intel/tbb/include -I/usr/include -I/usr/local/cuda/include -I/usr/include/nvidia-346/CL/c
-- Generating temporary cmake readable file: /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.depend.tmp
/usr/bin/cmake -D input_file:FILEPATH=/home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.NVCC-depend -D output_file:FILEPATH=/home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.depend.tmp -P /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake
-- Copy if different /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.depend.tmp to /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.depend
/usr/bin/cmake -E copy_if_different /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.depend.tmp /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.depend
-- Removing /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.depend.tmp and /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.NVCC-depend
/usr/bin/cmake -E remove /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.depend.tmp /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o.NVCC-depend
-- Generating /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/./osd_static_gpu_generated_cudaKernel.cu.o
/usr/local/cuda/bin/nvcc /home/pion/ext/openSubdiv-current/opensubdiv/osd/cudaKernel.cu -c -o /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/./osd_static_gpu_generated_cudaKernel.cu.o -ccbin /usr/bin/cc -m64 -DOPENSUBDIV_VERSION_STRING=\"3.0.0.beta\" -DOPENSUBDIV_HAS_OPENMP -DOPENSUBDIV_HAS_TBB -DGLFW_VERSION_3 -DOSD_USES_GLEW -DOPENSUBDIV_HAS_GLSL_TRANSFORM_FEEDBACK -DOPENSUBDIV_HAS_GLSL_COMPUTE -DOPENSUBDIV_HAS_OPENCL -DOPENSUBDIV_HAS_CUDA -DOPENSUBDIV_HAS_PTEX -DOPENSUBDIV_HAS_MAYA -Xcompiler ,\"-O3\",\"-DNDEBUG\" -Xcompiler -fPIC --gpu-architecture compute_20 --gpu-code sm_30 -DNVCC -I/usr/local/cuda/include -I/home/pion/ext/openSubdiv-current/opensubdiv -I/home/pion/ext/ptex-current/install/include -I/opt/intel/tbb/include -I/usr/include -I/usr/local/cuda/include -I/usr/include/nvidia-346/CL/c
/home/pion/ext/openSubdiv-current/opensubdiv/osd/cudaKernel.cu(223): warning: type qualifier is meaningless on cast type

/home/pion/ext/openSubdiv-current/opensubdiv/osd/cudaKernel.cu(223): warning: type qualifier is meaningless on cast type

Generated /home/pion/ext/openSubdiv-current/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/./osd_static_gpu_generated_cudaKernel.cu.o successfully.
[ 27%] Building CXX object opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/version.cpp.o
Linking CXX shared library ../lib/libosdGPU.so
[ 27%] Built target osd_dynamic_gpu
[ 27%] Building CXX object opensubdiv/CMakeFiles/osd_static_cpu.dir/version.cpp.o
Linking CXX static library ../lib/libosdCPU.a
[ 27%] Built target osd_static_cpu
[ 27%] Building CXX object opensubdiv/CMakeFiles/osd_static_gpu.dir/version.cpp.o
Linking CXX static library ../lib/libosdGPU.a
[ 28%] Built target osd_static_gpu
[ 29%] Building CXX object regression/common/CMakeFiles/regression_common_obj.dir/shape_utils.cpp.o
[ 29%] Built target regression_common_obj
[ 29%] Building CXX object regression/common/CMakeFiles/regression_vtr_utils_obj.dir/vtr_utils.cpp.o
[ 29%] Built target regression_vtr_utils_obj
[ 30%] Building CXX object regression/hbr_regression/CMakeFiles/hbr_baseline.dir/baseline.cpp.o
Linking CXX executable ../../bin/hbr_baseline
[ 30%] Built target hbr_baseline
[ 31%] Building CXX object regression/hbr_regression/CMakeFiles/hbr_regression.dir/main.cpp.o
Linking CXX executable ../../bin/hbr_regression
[ 31%] Built target hbr_regression
[ 32%] Building CXX object regression/vtr_regression/CMakeFiles/vtr_regression.dir/vtr_regression.cpp.o
Linking CXX executable ../../bin/vtr_regression
[ 32%] Built target vtr_regression
[ 33%] Generating ssao.gen.h
[ 33%] Generating framebuffer.gen.h
Scanning dependencies of target examples_common_obj
[ 33%] Building CXX object examples/common/CMakeFiles/examples_common_obj.dir/font_image.cpp.o
[ 34%] Building CXX object examples/common/CMakeFiles/examples_common_obj.dir/hdr_reader.cpp.o
[ 34%] Building CXX object examples/common/CMakeFiles/examples_common_obj.dir/hud.cpp.o
[ 34%] Building CXX object examples/common/CMakeFiles/examples_common_obj.dir/objAnim.cpp.o
[ 35%] Building CXX object examples/common/CMakeFiles/examples_common_obj.dir/patchColors.cpp.o
[ 35%] Building CXX object examples/common/CMakeFiles/examples_common_obj.dir/gl_common.cpp.o
[ 35%] Building CXX object examples/common/CMakeFiles/examples_common_obj.dir/gl_framebuffer.cpp.o
[ 36%] Building CXX object examples/common/CMakeFiles/examples_common_obj.dir/gl_hud.cpp.o
[ 36%] Built target examples_common_obj
[ 37%] Generating shader_gl3.gen.h
[ 37%] Generating shader.gen.h
Scanning dependencies of target glViewer
[ 37%] Building CXX object examples/glViewer/CMakeFiles/glViewer.dir/glViewer.cpp.o
In file included from /usr/local/cuda/include/CL/opencl.h:44:0,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/../osd/opencl.h:34,
                 from /home/pion/ext/openSubdiv-current/opensubdiv/osd/clGLVertexBuffer.h:31,
                 from /home/pion/ext/openSubdiv-current/examples/glViewer/glViewer.cpp:66:
/usr/local/cuda/include/CL/cl_gl_ext.h:44:4: warning: "/*" within comment [-Wcomment]
  * /* cl_VEN_extname extension  */
 ^
Linking CXX executable ../../bin/glViewer
/home/pion/ext/glfw-current/build/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x1aeb): undefined reference to `XineramaQueryExtension'
x11_init.c:(.text+0x1b05): undefined reference to `XineramaIsActive'
/home/pion/ext/glfw-current/build/lib/libglfw3.a(x11_monitor.c.o): In function `_glfwPlatformGetMonitors':
x11_monitor.c:(.text+0x6fb): undefined reference to `XineramaQueryScreens'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/glViewer] Error 1
make[1]: *** [examples/glViewer/CMakeFiles/glViewer.dir/all] Error 2
make: *** [all] Error 2
</pre></code>

However, as long as I don't build the examples, the rest of the codebase compiles just fine against the CUDA 7 Toolkit.

**Comment by jcowles** [comment]
Hi Lindsey, looks like we may just need to tweak the linker flags -- thanks for reporting this!

**Comment by jcowles** [comment]
This should be fixed now -- please reopen if that's not the case!
