### ISSUE TITLE
RC1 : CMake configuration issues

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#603]
Hi,

  Not sure where to post RC1 stuff at the moment.

  The build configuration seems to have change alot from the dev branch.

  There is no longer variables to disable/enable components to be build, by components I mean Maya, CUDA, OpenCL

  This means that I must have a fully stocked development platform to be able to build OpenSubdiv.

  Previously, I could disable certain components so that I can build the basic libraries.

  Is the roadmap for OpenSubdiv going to be tied Maya+CUDA+OpenCL ?

Cheers

**Comment by jcowles** [comment]
Hey Nicholas, what exactly are you seeing? All the "NO_*" flags are still there (NO_MAYA, etc), are they not working for you?

Even if you don't set these flags, the build should continue and only compile what is available based on the dependencies present on your system.

**Comment by nyue** [comment]
My bad, I jump to "ReleaseCandidate_1_0" which is totally different from the new "v3_0_0_RC1"
All is well.
I have similar "XineramaQueryScreens" issues on CentOS, I will submit a different ticket.
Cheers

**Comment by jcowles** [comment]
Ah yeah, that is confusing! You should be good to go now, at least on the dev branch.
