### ISSUE TITLE
RC1 : XineramaQueryScreens missing symbols

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#604]
Hi,

  I thought I'd chime in since we are on the release candidate phase.

  On CentOS 6.4, there is also a need to link with Xinerama library so it is not just Ubuntu that has the issue.

[ 35%] Building CXX object regression/osd_regression/CMakeFiles/osd_regression.dir/main.cpp.o
Linking CXX executable ../../bin/osd_regression
/corp/projects/eng/nyue/Systems/glfw/v3.1.1/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x1af0): undefined reference to `XineramaQueryExtension'
x11_init.c:(.text+0x1b0a): undefined reference to `XineramaIsActive'
/corp/projects/eng/nyue/Systems/glfw/v3.1.1/lib/libglfw3.a(x11_monitor.c.o): In function `_glfwPlatformGetMonitors':
x11_monitor.c:(.text+0x6fc): undefined reference to `XineramaQueryScreens'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/osd_regression] Error 1
make[1]: *** [regression/osd_regression/CMakeFiles/osd_regression.dir/all] Error 2
make: *** [all] Error 2

Cheers

**Comment by jcowles** [comment]
This should be fixed now -- please reopen if that's not the case!
