### ISSUE TITLE
Unknown CMake command "_add_doxy_headers".

### ISSUE THREAD

**Issue by thomthom** [PixarAnimationStudios/OpenSubdiv#611]
Trying to build 3.0.0 RC1 (335596236b2d7857a0a4f9ead94765ff11eb8086) on Windows 7 using the following command: (minimal with no dependencies)

```
cmake ^
  -G "Visual Studio 12 2013" ^
  -DNO_EXAMPLES=1 ^
  -DNO_TUTORIALS=1 ^
  -DNO_REGRESSION=1 ^
  -DNO_MAYA=1 ^
  -DNO_PTEX=1 ^
  -DNO_DOC=1 ^
  -DNO_OMP=1 ^
  -DNO_TBB=1 ^
  -DNO_CUDA=1 ^
  -DNO_OPENCL=1 ^
  -DNO_OPENGL=1 ^
  -DNO_CLEW=1 ^
  ..
```

This yields an error message about missing command `_add_doxy_headers`:

```
CMake Error at sdc/CMakeLists.txt:59 (_add_doxy_headers):
  Unknown CMake command "_add_doxy_headers".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.0)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "C:/Users/tthomas2/SourceTree/OpenSubdiv/opensubdiv/build/CMakeFiles/CMakeOutput.log".
```

Log file: https://gist.github.com/thomthom/799971e568d73e6ebb0b

Is doxygen required?

**Comment by jcowles** [comment]
The CMake errors seem suspicious -- what version of CMake are you running?

**Comment by thomthom** [comment]
CMake 3.0.1

When it says 2.8 under requirements I assumed newer was ok - but does it have to be that exact version?

I see the latest version of CMake is now 3.2.3.

**Comment by jcowles** [comment]
Yeah, that should be fine, we'll try to reproduce the problem on our end, thanks!

--
Jeremy

Sent from my phone

**Comment by jcowles** [comment]
I was unable to reproduce the issue on Linux using CMake 2.8, we'll also give it a try on Windows.

**Comment by takahito-tejima** [comment]
I have cmake 3.2.2 installed on windows and it works for me with minimal dependencies.

**Comment by thomthom** [comment]
Could it be because I don't have doxygen or anything else installed?
I'll try tomorrow with updated version of CMake. Maybe even pull the repo fresh.

**Comment by c64kernal** [comment]
I don't have doxygen installed, and I tried with the same defines as noted here and I was able to compile on Win 8.1 with cmake 3.1.1.

**Comment by thomthom** [comment]
I updated to CMake 3.2.3 and cleaned my %PATH% as the CMake install complained it was unable to add CMake to PATH as it had apparently reached its max size. Before I had used full path to CMake.
I also cleaned out the repo and fetched it again.

This time it all seemed to work fine. Not sure what the root cause was previously, but at least it works now.

Noticed a warning about GLFW - saying it was not found but is required. I thought it was optional... ?

```
-- Could NOT find GLFW (missing:  GLFW_INCLUDE_DIR GLFW_LIBRARIES) (Required is at least version "3.0.0")
-- Found DXSDK: C:/Program Files (x86)/Windows Kits/8.1/Include/um
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/tthomas2/SourceTree/OpenSubdiv/build
```

**Comment by jcowles** [comment]
Cool, my guess is that it was related to your PATH

Glfw should be optional, I think this is an existing build problem, we'll look into it

--
Jeremy

Sent from my phone

**Comment by wallisc** [comment]
For anyone else who might hit this in the future, I hit this exact issue when running cmake in the <github directory>/opensubdiv instead of in the parent directory <github directory>/.  This is due to the _add_doxy_headers macro being defined in the parent directory
