### ISSUE TITLE
cmake fails to set CUDA_TOOLKIT_ROOT_DIR

### ISSUE THREAD

**Issue by opeca64** [PixarAnimationStudios/OpenSubdiv#616]
As mentioned in #472, the variable, <code>CUDA_SDK_ROOT_DIR</code> doesn't get set for Linux users using <code>cmake</code> even though it does find Cuda.  On Linux ( Ubuntu 14.04.1 ) this variable doesn't get automatically set during installation of Cuda ( like it does through the "installer" distributed for Windows users. )

For reference, my <code>CUDA_SDK_ROOT_DIR</code> is <code>${CUDA_TOOLKIT_ROOT_DIR}/samples/common</code>, which resolves to: <code>/usr/local/cuda/samples/common</code>. The good news, is that a typical linux user will only have to fix it once in <code>ccmake</code> because it's not set from any file tracked in the repository. I'd suggest using one of the existing <code>FindXXXX.cmake</code> file as a template.

**Comment by manuelk** [comment]
For CUDA we are using the FindCUDA module that ships with CMake, so if I understand the issue correctly, this issue is out of our hands. This CMake module is unfortunately rather overly complex, so finding the right set of variables to override the configuration might not be simple...

**Comment by opeca64** [comment]
Hi Manuel,  there have been a few updates since I opened this ticket and I'm not an expert in cmake.  It might take me some time to properly get to all this as I'm in the middle of a delivery and I won't be able to even revisit this till the weekend.  

Thanks for the information - you're absolutely right - cmake already provides a module for finding CUDA: https://cmake.org/cmake/help/v3.4/module/FindCUDA.html.  

Back in June, nvidia had recently ( and rather quietly ) taken over maintenance of cuda and the drivers for Ubuntu.  It's not surprising to hear that this might be an issue with cmake. I'll be happy to do a little bit of digging in the existing module from CMake to see if this bug is platform-specific or still a problem, and I'll close this if it's not.

**Comment by opeca64** [comment]
Hey, so I did get around to this, however many of the build issues that I had previously were still occurring... I'm going to have to go and make all of the fixes again.  Update should be incoming considering there's a blizzard here...

**Comment by davidgyu** [comment]
Hi, We think this is working correctly in the 3.x releases. As documented here:
  https://cmake.org/cmake/help/v3.0/module/FindCUDA.html
The CUDA_TOOLKIT_ROOT_DIR is something that the user might need to set manually if it cannot be determined automatically.

One typical use case of this is when there are multiple versions of the CUDA toolkit installed on a system. For example several of my test machines have v5.5, v7.0, and v7.5 installed and on those systems I configure OpenSubdiv by specifying "-DCUDA_TOOLKIT_ROOT_DIR=<path_to_the_desired_version>" on the cmake command line. Thanks!
