### ISSUE TITLE
MSVCPRT LNK2005

### ISSUE THREAD

**Issue by MidnightCow2016** [PixarAnimationStudios/OpenSubdiv#634]
Hi,

I'm trying to incorporate the code from the OSD Tutorial0 ( the CPU compute context one ) into a plugin i am working on.  I have got to the point where i cannot get past this particular error:

```
msvcprt.lib(MSVCP100.dll) : error LNK2005: "public: void __cdecl std::_Container_base0::_Orphan_all(void)" (?_Orphan_all@_Container_base0@std@@QEAAXXZ) already defined in MyPlugin.obj
```

So far i have managed to successfully get rid of a bunch of similar errors, by adding LIBCMT and LIBCPMT to the Ignore list in the Linker properties - but when i add MSVCPRT to this list i get a ton of Unresolved Externals from the included osdCPU lib.

To add to this, when i build my project as Multi-Threaded DLL (/MD) it builds successfully.  But does not work in my plugins host application which requires Multi-Threaded (/MT) only to run..

So at this point i'm looking for any suggestions, as i'm a bit stuck :/

I've tried various things including building osdCPU and it's dependencies as /MT in line with my project, as well as various other options, but so far always end up with this MSVCPRT issue.

I understand this is more my own problem and outwith the issues remit of the OSD library itself, but any suggestions would be greatly appreciated!

**Comment by davidgyu** [comment]
This has been addressed by PR #917 which added an option to build the OpenSubdiv libraries with static CRT linkage. This option was added specifically in support of linking OpenSubdiv with plugin code. Thanks!
