### ISSUE TITLE
Compile error on iOS with Xcode 7

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenSubdiv#648]
This line won't compile (two places in fvarRefinement.cpp):
                cVertEdgeBuffer[i] = _refinement.getEdgeChildEdges(pVertEdges[i])[pVertInEdge[i]];

I hacked around it by adding a setAtIndex method to StackBuffer.
                cVertEdgeBuffer.setAtIndex(i, _refinement.getEdgeChildEdges(pVertEdges[i])[pVertInEdge[i]]);

The error is pasted below. I assume it has something to do with sizeof int making overloads ambiguous, but I'm not sure. Posting here in case anyone has ideas.

extern/opensubdiv/vtr/fvarRefinement.cpp:592:32: error: use of overloaded operator '[]' is ambiguous (with operand types 'internal::StackBuffer<Index, 16>' and 'int')
                cVertEdgeBuffer[i] = a;
                ~~~~~~~~~~~~~~~^~
In file included from 
extern/opensubdiv/vtr/fvarRefinement.cpp:27:
extern/opensubdiv/vtr/../vtr/stackBuffer.h:62:18: note: candidate function
    TYPE &       operator[](size_type index)        { return _data[index]; }
                 ^
extern/opensubdiv/vtr/../vtr/stackBuffer.h:63:18: note: candidate function
    TYPE const & operator[](size_type index) const  { return _data[index]; }
                 ^

extern/opensubdiv/vtr/fvarRefinement.cpp:592:32: note: built-in candidate operator[](int *, int)
                cVertEdgeBuffer[i] = a;
                               ^
extern/opensubdiv/vtr/fvarRefinement.cpp:592:32: note: built-in candidate operator[](const int *, int)
extern/opensubdiv/vtr/fvarRefinement.cpp:592:32: note: built-in candidate operator[](volatile int *, int)
extern/opensubdiv/vtr/fvarRefinement.cpp:592:32: note: built-in candidate operator[](const volatile int *, int)
extern/opensubdiv/vtr/fvarRefinement.cpp:663:28: error: use of overloaded operator '[]' is ambiguous (with operand types 'internal::StackBuffer<Index, 16>' and 'int')
            cVertEdgeBuffer[i] = _refinement.getEdgeChildEdges(pVertEdges[i])[pVertInEdge[i]];
            ~~~~~~~~~~~~~~~^~
In file included from 
extern/opensubdiv/vtr/fvarRefinement.cpp:27:
extern/opensubdiv/vtr/../vtr/stackBuffer.h:62:18: note: candidate function
    TYPE &       operator[](size_type index)        { return _data[index]; }
                 ^
extern/opensubdiv/vtr/../vtr/stackBuffer.h:63:18: note: candidate function
    TYPE const & operator[](size_type index) const  { return _data[index]; }
                 ^
extern/opensubdiv/vtr/fvarRefinement.cpp:663:28: note: built-in candidate operator[](int *, int)
            cVertEdgeBuffer[i] = _refinement.getEdgeChildEdges(pVertEdges[i])[pVertInEdge[i]];
                           ^
extern/opensubdiv/vtr/fvarRefinement.cpp:663:28: note: built-in candidate operator[](const int *, int)
extern/opensubdiv/vtr/fvarRefinement.cpp:663:28: note: built-in candidate operator[](volatile int *, int)
extern/opensubdiv/vtr/fvarRefinement.cpp:663:28: note: built-in candidate operator[](const volatile int *, int)
2 errors generated.

**Comment by barfowl** [comment]
We were also getting this with 32-builds in MSVC and addressed it in Issue #625 (operator[] was entirely removed to eliminate the ambiguity).

Could you update to get the RC2 version that was issued since and see if you can build with that.

Thanks

**Comment by meshula** [comment]
That's good, thanks!

One other fiendishly minor tweak, if you wouldn't mind ~

        snprintf(msg, 1024, "%s - "format, errStr, ##__VA_ARGS__); \

It doesn't like "format (doesn't compile), so I've been changing this manually -

        snprintf(msg, 1024, "%s - " format, errStr, ##__VA_ARGS__); \

**Comment by barfowl** [comment]
Okay, that seems harmless -- I opened pull request #651.

I was surprised by both of your problems as others in the team have been compiling successfully for iOS without issue.  It was only 32-bit builds with MSVC that initially triggered the ambiguity error (which we now build) but this one with the string concatenation is a new one.
