### ISSUE TITLE
FAR Tutorial 7 (Cascading Stencils) does not generated the correct result

### ISSUE THREAD

**Issue by dazcjones** [PixarAnimationStudios/OpenSubdiv#694]
FAR Tutorial 7, that demonstrates the use of cascading stencils, does not seem to work correctly in release 3.0.  It applies the edit, but the resulting mesh seems to be scaled down or loses volume on each iteration of subdivision.

**Comment by dazcjones** [comment]
Looking at it more closely, it looks like the StencilTableFactory::Create method ignores the "factorizeIntermediateLevels" options and always factorizes the weights of all levels.

**Comment by jcowles** [comment]
Yes indeed, this is a bug -- thanks for reporting and digging into it!

We will have a fix soon.

--
Jeremy

**Comment by dazcjones** [comment]
From my examination, the "factorizeIntermediateLevels" needs to be passed on to the internal "WeightTable" class from "stencilBuilder.cpp" or that "WeightTable" needs its "_coarseVertCount" member updated after each iteration.  Not sure which is the preferable solution or if there may be a better one, but those looked like the simplest and most localized.

**Comment by dazcjones** [comment]
I see you have a "dev-stencilfix" in jcowles/OpenSubdiv, is that branch in a state that's worth pulling and trying?

**Comment by dazcjones** [comment]
I tried the fix in "jcowles/OpenSubdiv/dev-stencilfix" it does seem to fix the issue.

**Comment by jcowles** [comment]
Thanks for the verification, I'll pull request this soon.

--
Jeremy

**Comment by jcowles** [comment]
I went with a simpler fix (updating coarse verts, one of the options you initially suggested) -- if you have time, would you mind testing again with this alternate fix (in PR #709)?

**Comment by dazcjones** [comment]
The alternate fix seems to to work as well.

**Comment by davidgyu** [comment]
This was fixed by PR#709
