### ISSUE TITLE
Multiple definitions a linking stage

### ISSUE THREAD

**Issue by cedricp** [PixarAnimationStudios/OpenSubdiv#708]
Hi, I had a problem linking OSD against blender, the linker always reported a multiple definition of the function "convertToCompatibleStencilTable". I have been able to remove this error by just declaring these 4 functions "inline" in osd/mesh.h

**Comment by cedricp** [comment]
Forgot to mention I'm using GCC 4.8 under Linux

**Comment by cedricp** [comment]
It seems someone already found that : https://github.com/PixarAnimationStudios/OpenSubdiv/pull/703

**Comment by jcowles** [comment]
Cedric, #703 was merged, so this should be fixed now, but please reopen if you continue to have issues.
