### ISSUE TITLE
Fractional Tess broken ? 

### ISSUE THREAD

**Issue by manuelk** [PixarAnimationStudios/OpenSubdiv#711]
D3D & GL viewer seem to not be doing fractional tessellation any more (ie. toggling the button does nothing) - this is in the master branch btw.

M.

**Comment by davidgyu** [comment]
Hi Manuel,

Yes, this is a known limitation of our method of handling tessellation of transition edges.

The current Osd tessellation shader code no longer partitions transition patches into sub-patches, instead tessellation parameterization along transition edges is computed dynamically in OsdGetTessParameterization(). We haven't yet implemented a version of this method which is compatible with fractional tessellation, although we do plan to do so.

I'll add a note about this to the release notes.

Thanks!
-David

**Comment by manuelk** [comment]
I was guessing something along those lines - thanks for the confirmation.

M.

**Comment by manuelk** [comment]
Fixed - closing
