### ISSUE TITLE
Compile issue with ptex and libz

### ISSUE THREAD

**Issue by stevenleecinetec** [PixarAnimationStudios/OpenSubdiv#730]
Hello,

I'm having difficulties compiling.
I'm using Ubuntu 14.04, with ptex 2.0.62.
I though I have set up everything properly, but clearly I haven't - i've spent hours but I can't seem to get it!
When I make, the compiler complains and fails with the following error msg:

Linking CXX executable ../../bin/glPtexViewer
../../ptex/install/lib/libPtex.a(PtexReader.o): In function `PtexReader::readZipBlock(void*, int, int)':
PtexReader.cpp:(.text+0x12b3): undefined reference to`inflate'
PtexReader.cpp:(.text+0x12f6): undefined reference to `inflateReset'
PtexReader.cpp:(.text+0x1369): undefined reference to`inflateReset'
../../ptex/install/lib/libPtex.a(PtexReader.o): In function `PtexReader::~PtexReader()':
PtexReader.cpp:(.text+0x1f04): undefined reference to`inflateEnd'
../../ptex/install/lib/libPtex.a(PtexReader.o): In function `PtexReader::PtexReader(void**, PtexCacheImpl*, bool, PtexInputHandler*)':
PtexReader.cpp:(.text+0x25c6): undefined reference to`inflateInit_'
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/glPtexViewer] Error 1
make[1]: **\* [examples/glPtexViewer/CMakeFiles/glPtexViewer.dir/all] Error 2
make: **\* [all] Error 2

After some researching, I believe this is a linking issue with libz.
However, Ptex did compile without any issues on its own.
I can't seem to find where to link libz ("-lz") either.

Any help would be greatly appreciated!
Please let me know if you need any further information.
Thanks!

Steven

**Comment by jtran56** [comment]
Filed as internal issue #151656.

**Comment by davidgyu** [comment]
Marking this as closed since this is working correctly in our testing with recent Ubuntu releases (18.04 and 20.04).
Please reopen or file a new ticket if this is still a problem. Thanks!
