### ISSUE TITLE
Tutorial 6 is misleading when using maxIsolation for maximum level

### ISSUE THREAD

**Issue by shengfuintel** [PixarAnimationStudios/OpenSubdiv#732]
In far/turotial6, when interpolate vertex primvar data, the code is like the following:

    Vertex * src = &verts[0];
    for (int level = 1; level <= maxIsolation; ++level) {
        Vertex * dst = src + refiner->GetLevel(level-1).GetNumVertices();
        Far::PrimvarRefiner(*refiner).Interpolate(level, src, dst);
        src = dst;
    }

However, I think use maxIsolation as the maximum level is misleading since for feature adaptive subdivision, maximum level may be less than maxIsolation. The Interpolate function will throw out an assertion. 

I suggest to change to the following:

    for (int level = 1; level <=  refiner->GetMaxLevel(); ++level) {
        Vertex * dst = src + refiner->GetLevel(level-1).GetNumVertices();
        Far::PrimvarRefiner(*refiner).Interpolate(level, src, dst);
        src = dst;
    }

**Comment by davidgyu** [comment]
Fixed by https://github.com/PixarAnimationStudios/OpenSubdiv/pull/777
