### ISSUE TITLE
Adaptive subdivision not displaying on Intel

### ISSUE THREAD

**Issue by significant-bit** [PixarAnimationStudios/OpenSubdiv#757]
Adaptive subdivision doesn't seem to work on Intel chips. No crash or errors; the surface just doesn't appear on screen. Non-adaptive displays fine.

I suspect it's a GL drawing issue since the surface is invisible for CPU and GPU evaluators.

Ran OpenSubdiv 3.0.3 glViewer & glFVarViewer on these systems:
Intel HD 4000, Mac OS 10.11
Intel HD 4600, Windows 10

glFVarViewer also shows some interesting geometry in the right pane:

![glfvarviewer intel](https://cloud.githubusercontent.com/assets/2501283/10991332/46915da8-842a-11e5-9157-8af5b0b6a39a.png)

**Comment by takahito-tejima** [comment]
Hi Mike,

Could you try to comment out the following line of the tess eval shader 
in opensubdiv/osd/glslPatchBSpline.glsl ?

...
194:   // gl_Position = OsdProjectionMatrix() * outpt.v.position;
...

When I looked a similar problem before, it seems intel's GLSL compiler 
doesn't allow duplicated assignments to gl_Position in both tessellation 
and geometry stages.

thanks!
takahito

**Comment by significant-bit** [comment]
Commenting out that line puts *something* on the screen but not the whole surface. On Intel HD 4000:

![intel hd 4000](https://cloud.githubusercontent.com/assets/2501283/11234628/d1736ef4-8d97-11e5-9a9b-f28ecca0f4dc.png)

nVidia GT 650M (same laptop) shows the whole surface, with or without that line in the shader.

![nvidia gt 650m](https://cloud.githubusercontent.com/assets/2501283/11234656/28910f48-8d98-11e5-8241-d1db0097c99c.png)

Anything else I can try?

**Comment by jcowles** [comment]
Hey Mike, I created a thread on the Intel forums:
https://software.intel.com/en-us/forums/graphics-driver-bug-reporting/topic/604613

**Comment by jcowles** [comment]
@significant-bit Intel is requesting more information, would you mind filling in the details of your setup on that forum?

**Comment by significant-bit** [comment]
Sure thing, after work today.

**Comment by salvager2014** [comment]
no iwant get a new price and an other thing or you give me something do it？ 发自网易邮箱大师 On 2015-12-15 02:31 , Jeremy Cowles Wrote: @significant-bit Intel is requesting more information, would you mind filling in the details of your setup on that forum? — Reply to this email directly or view it on GitHub.

**Comment by jcowles** [comment]
Thanks!

**Comment by jcowles** [comment]
Thanks again for the excellent info on the Intel forum!

**Comment by manuelk** [comment]
Not really contributing a solution but I spent a few days a while back to get OSD running on an Iris Pro GPU : i believe i got all the tess code working at the time. I was eventually able to run the Barbarian demo, but the drivers were buggy and i wasn't able to get the GLSL compute kernels to compile.

**Comment by c64kernal** [comment]
The good news is that Intel said they fixed this.  They did not, however, yet post an ETA for the public version of the driver (as of 05/06/2016).  But I'll close this issue out here and we can continue to track progress on the Intel forum.
