### ISSUE TITLE
Transform Feedback crashes on Mac, nVidia GT 650M

### ISSUE THREAD

**Issue by significant-bit** [PixarAnimationStudios/OpenSubdiv#758]
*The crash is in the GL driver, so I opened a bug report with Apple on 16 Oct 2015 (Radar 23154198). Re-reporting here so people are aware of the issue.*

Summary:
The sample programs that come with Pixar's OpenSubdiv library crash when using Transform Feedback. TF is used to compute stencil values needed for quick surface evaluation. TF is also used to evaluate the surface, but it crashes at earlier stencil stage so whether that works is unknown.

Steps to Reproduce:
1) build OpenSubdiv 3.0.3
2) run the glViewer sample program (or any of its friends)
3) switch from CPU to GLSL Transform Feedback

Expected Results:
Visuals should look identical to CPU path, but with a higher frame rate.

Actual Results:
Crash in nVidia driver:

com.apple.GeForceGLDriver (unknown function)
gldUpdateTransformFeedbackState
GLXFBEvaluator::EvalStencils (part of OpenSubdiv)

Version:
Mac OS 10.11 (15A284)
Mac OS 10.11.1 (15B42)

Notes:
As part of the Blender project, I'm trying to get OpenSubdiv working on Mac as well as it does on other platforms.

No GL errors detected leading up to the fatal call to glBeginTransformFeedback.

Intel HD 4000 on same machine does not crash.

Configuration:
MacBook Pro mid-2012 with nVidia GT 650M

**Comment by significant-bit** [comment]
Crash was fixed in Mac OS 10.11.2. Yay!

**Comment by jcowles** [comment]
Sweet, thanks Mike!

--
Jeremy
