### ISSUE TITLE
LocationArrayVec usage.

### ISSUE THREAD

**Issue by DanielGeorge** [PixarAnimationStudios/OpenSubdiv#787]
I’m having a little trouble understanding the usage of stencil tables. I’m trying to get the limit surface derivatives so I can compute the normals of a mesh. Up to now I’m using `Far::PrimvarRefiner(*refiner).Limit` to get the limit surface. 

When trying to use a limit stencil table I can’t seem to understand how to fill those LocationArray’s. All the examples I’ve seen that compute the limit stencil table fill that LocationArrayVec with a list of random:

```
for (int face=0, count=0; face<nfaces; ++face) 
{
        for (int sample=0; sample<nsamples; ++sample, ++count) 
        {
            float s = (float)rand()/(float)RAND_MAX,
                    t = (float)rand()/(float)RAND_MAX;
            Far::PatchTable::PatchHandle const * handle = patchmap.FindPatch(face, s, t);
       }
}
```

How would I compute those S,T parameters to fill the LocationArrayVec for the vertices of a mesh and eventually calculate the limit surface derivatives? 

Any help would be greatly appreciated.

**Comment by manuelk** [comment]
Sorry - i don't think there is an easy way to do this from the existing factory (we needed arbitrary locations pushed to the limit, not the verts of the mesh)

Here's one way that should work:

```
foreach vert in mesh:

    if not vert.isextraordinary:    
        faces = refiner.GetVertFaces(vert)
        fverts = refiner.GetFaceVerts(faces[0])
        vertIndex = index of vert in fverts
        s,t = map vertIndex (vert0=(0,0), vert3=(1,1)...)
        location = (faces[0], s, t)
    else:
        find bottom level child face
        same method as above to find (s,t)
```

**Comment by DanielGeorge** [comment]
Ah, I see. Thanks a lot. I'll give it a try. So If I understand correctly Stencil Tables are mostly used for occasions where you need arbitrary locations. Maybe I should be looking at Patch Tables or just stick to using Far::PrimvarRefiner().Limit to get the derivatives?

**Comment by manuelk** [comment]
Actually, the main use-case for stencils is evaluating animated patch verts. The limit stencils are more a by-product of how easy it is to factorize b-spline weights in the patch tables, which is why that factory never really tried to just produce them for control mesh verts. 

Given the (somewhat new)  PrimvarRefiner.Limit code, it would probably be nice to bridge that gap with a LimitStencil factory, because that limit function is not cheap and you definitely want to factorize those weights if they are being re-used.

**Comment by DanielGeorge** [comment]
That would be ideal. Since control points are already known to OSD, computing the limit stencils should be somewhat transparent. I found these functions in Blenders code that look useful in getting those S, T parameters:

```
int ccg_gridsize(int level)
{
    return (1 << (level - 1)) + 1;
}

void mapGridToFace(int S, float grid_u, float grid_v, float *face_u, float *face_v)
{
    float u, v;    
    u = 0.5f - 0.5f * grid_u;
    v = 0.5f - 0.5f * grid_v;
    
    if (S == 0) { *face_u = v; *face_v = u; }
    else if (S == 1) { *face_u = 1.0f - u; *face_v = v; }
    else if (S == 2) { *face_u = 1.0f - v; *face_v = 1.0f - u; }
    else { *face_u = u; *face_v = 1.0f - v; }
}
```

Based on your first replay, I think I have an idea of how to go and setup the Limit Stencil Table.

**Comment by manuelk** [comment]
This might be more work than you need to do - if you have the farViewer built, try turning on the textures and look at how the (s,t) spaces rotate around verts.

**Comment by DanielGeorge** [comment]
Ok, I think I see how it's done now. Thank you for pointing me to that. I'm uncertain though if I actually need a stencil table. This is going to be used in a modeling application where there is no animation involved. I was going to use them solely to compute the normals for the limit mesh and update positions after deformations. So I'm wondering since Limit Stencils need Patch Tables to compute the final derivatives, maybe I should be using a Patch table directly and skip the creation of stencil tables (if thats possible) ?

Basically these are the things I would like get access to
1) Compute Limit Normals
2) Draw refined edges. Now I'm using some recursion to get from parent cage edge to children edges. 
3) Material id for each face so I know how to draw it. Currently I'm passing this as a primevar, and interpolate per face. This seems like a right way to do it unless I'm overlooking something in Pach Tables.

Based on those, what would be a good usage scenario? Should I skip Stencil Tables all together and maybe look a little more into Patch Tables?

**Comment by manuelk** [comment]
Probably : assuming your app only moves small sets of verts at a time, recomputing just those should be OK.
Mathematically speaking, stencils are just fancy factorizations of linear interpolation weights as a way of caching pre-computations.

**Comment by DanielGeorge** [comment]
Ah I see. Excellent, I'll give patch tables a closer look, thank you very much for your help!
