### ISSUE TITLE
Remove requirement for GLFW, Doxygen, Docutils and PythonInterp in Cmake

### ISSUE THREAD

**Issue by RogersDoug** [PixarAnimationStudios/OpenSubdiv#796]
Could NOT find GLFW (missing:  GLFW_INCLUDE_DIR GLFW_LIBRARIES) (Required is at least version "3.0.0")
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) (Required is at least version "1.8.4")
Could NOT find Docutils (missing:  RST2HTML_EXECUTABLE) (Required is at least version "0.9")
Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) (Required is at least version "2.6")
Configuring done

These are not listed as requirement and should not be needed to build.

**Comment by RogersDoug** [comment]
It builds without these.  These are actually warnings.

**Comment by manuelk** [comment]
None of the these packages have the REQUIRED flag : the "required" part is the version. This default warning from CMake is somewhat ambiguous and could be improved...
