### ISSUE TITLE
mayaPolySmooth Maya plugin errors

### ISSUE THREAD

**Issue by RogersDoug** [PixarAnimationStudios/OpenSubdiv#797]
Maya Windows 10 x64

I get this error when loading the plug in:

`// Error: file: C:/Program Files/Autodesk/Maya2016/scripts/others/mayaPolySmooth.mel line 38: menu: Object '' not found. // `

**Comment by signalpillar** [comment]
Hi @RogersDoug I have the same problem in Maya 2016. 
I was able to fix it by renaming variable used to reference edit menu. New name is `gMainEditMeshMenu.mel`

**Comment by dnx4015** [comment]
Hi! @signalpillar I am trying to use the osd in Maya2016 but I get a assert(refiner) error (line 841 of file mayaPolysmooth. 
I wonder whether I might be missing something. I copied the mayaPolySmooth.mel to the scripts directory and the mayaPolySmooth.mll (exp, ilk, lib) to the plug-in directory. 
Do I need to copy anything else?

**Comment by signalpillar** [comment]
@dnx4015 Hi, sorry for my late response. Unfortunately, I haven't seen issue you described. 
Have you managed to solve it ?

**Comment by dnx4015** [comment]
I did not manage to solve it, but I desisted because the plugin for maya seems outdated. The one that comes embeded has way more controllers.

**Comment by manuelk** [comment]
This plugin was written a long time ago as an "implementation example". At this point, since Maya implements OSD as its default display mode, it is obsolete and I don't think anyone has been maintaining this code in a while...

**Comment by c64kernal** [comment]
Thanks for pointing this out.  This example is removed in 3.1.  David removed it in commit 8babf1e12bd763c5f8053dd54719a256025e742a
