### ISSUE TITLE
One line fix for broken HUD slider. 

### ISSUE THREAD

**Issue by fakebits** [PixarAnimationStudios/OpenSubdiv#801]
The slider widget in the HUD that you use for the examples is broken. There is a one line fix that I found that gets the sliders working correctly again.

in the file, /examples/common/hud.h line 133

value = v>0.0f ? floor(v+0.5f) : ceil(v-0.5f);

should be...

value = value>0.0f ? floor(value+0.5f) : ceil(value-0.5f);

Thats it. Sliders work correctly again. It looks like someone made a simple mistake a used the input v instead of the bounds checked value.

**Comment by c64kernal** [comment]
Thanks very much for pointing this out.  There was also another problem with sliders that should also be fixed with the same pull request (coming soon).  Thanks again!

**Comment by davidgyu** [comment]
Fixed by https://github.com/PixarAnimationStudios/OpenSubdiv/pull/803
