### ISSUE TITLE
CMakeLists: use OpenSubdiv_SOURCE_DIR instead of CMAKE_SOURCE_DIR

### ISSUE THREAD

**Issue by bmmund** [PixarAnimationStudios/OpenSubdiv#814]
Hello there,

I have a suggestion regarding the cmake scripts. I noticed that the CMAKE_SOURCE_DIR variable is used for establishing paths which can be problematic if you are incorporating OpenSubdiv build in your personal project using add_subdirectory(). Unless you have a reason for using CMAKE_SOURCE_DIR I would recommend using <Project_Name>_SOURCE_DIR instead. This would make OpenSubdiv more compatible with various dependancy management policies. For example, I like to subtree/submodule dependancies at a particular commit so that all collaborators are working with the same development environment. 

Here is a link to the documentation:
[CMAKE 2.8.6 <Project_Name>_SOURCE_DIR](https://cmake.org/cmake/help/v2.8.6/cmake.html#variable:Projectname_SOURCE_DIR)

Here is an example of it being used by GLFW:
[GLFW Example](https://github.com/glfw/glfw/blob/3.2/CMakeLists.txt)

**Comment by c64kernal** [comment]
Thanks Braden, that's a great suggestion!
