### ISSUE TITLE
Ptex CMake version detection is broken

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/OpenSubdiv#849]
I believe Ptex changed their version format, which OpenSubdiv now reports as version ".." and fails to use.

You can repro this by cloning Ptex, building it and then trying to use those includes in the OpenSubdiv build.

**Comment by jcowles** [comment]
I was building against this:
https://github.com/wdas/ptex.git

With the following config on windows:
cmake -G "Visual Studio 14 2015 Win64" ^
      -DCMAKE_INSTALL_PREFIX="..\inst\local" ^
      -DZLIB_INCLUDE_DIR="..\inst\local\include" ^
      -DZLIB_LIBRARY="..\inst\local\lib\zlib.lib" ^
      ..

// CPU count must be 1 (ptex build deps seem broken)
cmake --build . --target install --config Release -- /maxcpucount:1

**Comment by takahito-tejima** [comment]
Hi Jeremy, have you tried the dev branch? FindPtex has some fixes contributed from Manuel.

**Comment by jcowles** [comment]
Oh, yeah, that seems to work!
