### ISSUE TITLE
_StencilKernel and _PatchKernel deletes program twice

### ISSUE THREAD

**Issue by xtophyr** [PixarAnimationStudios/OpenSubdiv#880]
GLComputeEvaluator's _StencilKernel::Compile and _PatchKernel::Compile methods check for program, glDeleteProgram it, do some string init stuff, and then check and delete program again before assigning it.  This is probably harmless on most GL implementations, but unnecessary.
[patch.txt](https://github.com/PixarAnimationStudios/OpenSubdiv/files/524499/patch.txt)

**Comment by davidgyu** [comment]
Fixed by #925
