### ISSUE TITLE
Support getting 2nd partial derivatives with EvalPatches

### ISSUE THREAD

**Issue by DarkDefender** [PixarAnimationStudios/OpenSubdiv#904]
I've been waiting for the ability to get second partials with EvalPatches since #760.

I'm guessing I could just hack them into the CPU backend myself. But I would really like if I wouldn't have to rely on a forked version of opensubdiv to do this. (And I'm guessing pull requests won't be merged unless it's working on all backends)

Is there any ETA for this yet?

**Comment by davidgyu** [comment]
Ah, the core functionality is there already, but the interface plumbing has not been exposed.

We don't have a specific ETA yet, but we plan to address this soon.  Thanks!

**Comment by DarkDefender** [comment]
Yes, that is the problem. I'm sorry I were perhaps a bit vague in explaining the problem.
Good to know that you are planning making this happen soon. :)

**Comment by davidgyu** [comment]
Fixed by #924 #928 and #929 Thanks!
