### ISSUE TITLE
libglfw linking issue on CentOS-7

### ISSUE THREAD

**Issue by rskryptik61636** [PixarAnimationStudios/OpenSubdiv#909]
Hello,

I get this error message while trying to build OpenSubdiv on CentOS-7 64-bit.

> Scanning dependencies of target osd_regression
> [ 49%] Building CXX object regression/osd_regression/CMakeFiles/osd_regression.dir/main.cpp.o
> [ 49%] Linking CXX executable ../../bin/osd_regression
> /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
> /usr/bin/ld: note: 'XConvertSelection' is defined in DSO /lib64/libX11.so.6 so try adding it to the linker command line
> /lib64/libX11.so.6: could not read symbols: Invalid operation
> collect2: error: ld returned 1 exit status
> make[2]: *** [bin/osd_regression] Error 1
> make[1]: *** [regression/osd_regression/CMakeFiles/osd_regression.dir/all] Error 2
> make: *** [all] Error 2

I have glew-2.0.0 and glfw-3.2.1 installed under /usr and the cmake command I'm using is as follows:

> cmake -D NO_PTEX=1 -D NO_DOC=1 \
>       -D NO_OMP=1 -D NO_TBB=1 -D NO_CUDA=1 -D NO_OPENCL=1 -D NO_CLEW=1 \
>       -D GLEW_LOCATION="/usr" \
>       -D GLFW_LOCATION="/usr" \
>       ..

I used readelf to check if the two libraries were of different architectures but they seemed to both be 64-bit:

>   Class:                             ELF64
>   Machine:                           Advanced Micro Devices X86-64

Do I have to manually link against libX11.so?

**Comment by nyue** [comment]
Hi,

  Instead of linking against the static libglfw3.a, are you able to linking against the shared library version of GLFW. The shared library version will have its dependencies sorted out instead of you doing the hard work.

Cheers

**Comment by davidgyu** [comment]
That's a good suggestion nyue. Although, the default build configuration for glfw is still to build unshared libraries.

Fortunately, we just merged a fix into the dev branch that will allow OpenSubdiv examples to link correctly on linux w/ and w/o shared GLFW libs and also with the latest CMake and GLFW releases.

rskryptik61636, let us know if you are still seeing problems after merging: b0bdd90

Thanks!
-David

**Comment by rskryptik61636** [comment]
Awesome, that worked. Thanks so much :)
