### ISSUE TITLE
example/glFVarViewer crashes for shapes that have no UVs

### ISSUE THREAD

**Issue by barfowl** [PixarAnimationStudios/OpenSubdiv#923]
The glFVarViewer includes a list of compiled shapes and can accept additional shapes on the command line.  If any shape has no UVs, the app simply crashes without any indication of the cause -- clearly we can do better.

This was recently noted in #921 as the new catmark_fan shape that replaced the old in 3.1.1 did not include UVs.  I'll update glFVarViewer in the near future (hopefully) but just want to log it here as a known issue in the meantime.

**Comment by jtran56** [comment]
Filed as internal issue #142103.

**Comment by barfowl** [comment]
Fixed by #926
