### ISSUE TITLE
GPU patch shaders do not compute correct normals in common degenerate cases

### ISSUE THREAD

**Issue by barfowl** [PixarAnimationStudios/OpenSubdiv#947]
The patch shaders all appear to compute normals as the cross product of dPdu and dPdv and make no attempt to determine a well-defined normal when this cross product becomes zero -- either when one of two the partials is zero or when the two are parallel.

These situations are reasonably common, and the failure of the shaders to compute a well defined normal for them results in undesirable artifacts.  These visual artifacts have also been hindering adoption of new features that provide simpler (fewer) and more accurate patches for the limit surface.

Here is an example of three cases in the glViewer -- first illustrating the cages and patch coloring followed by the same shapes with simple normal shading for clarity: 

![before-patch](https://user-images.githubusercontent.com/4130807/30508533-eee8ef08-9a4d-11e7-80de-46d86452d333.png)

Left is a simple surface of revolution with four quads each with a degenerate edge at the pole.  Center is a simple smooth corner patch with an appropriately smooth boundary curve for the corner.  Right is an example of a smooth corner patch in the interior when infinitely sharp patches are enabled.

![before-normal](https://user-images.githubusercontent.com/4130807/30508534-f754d954-9a4d-11e7-8708-0b49be8a9cb2.png)

I have a fix for this issue that I will be submitting in the near future, but only for the GLSL versions (I'm unable to test others).

I'm opening this issue separately to better illustrate and discuss the problem here -- we may ultimately need multiple pull requests to fully address it.  There may also be some other issues that warrant further discussion, e.g. the choice of tolerance to test for degeneracy, possible change in behavior due to fixing a bug in normal derivative calculation, etc.

Fortunately both the BSpline and Gregory patch shaders make use of Bezier patch evaluation, and rewriting that in a way that efficiently allows detection and resolution of the degeneracy produces the following:

![after-normal](https://user-images.githubusercontent.com/4130807/30508540-1cf8b446-9a4e-11e7-9935-c4b0dd03ffad.png)

This should come at little or no added cost.  Based purely on operation counts, the revised evaluation is comparable to the existing evaluation and the added degeneracy test and determination of the correct normal is marginal.  Testing thus far indicates the revised evaluation may actually be slightly faster, but that testing has been limited.

And to clarify in closing, I am not advocating trying to resolve a degenerate normal in all cases where it may evaluate to zero.  The goal here is to address common cases that result from reasonable modeling practices, not those that may result from arbitrarily collapsing parts of the surface by deforming control points into coincidence with others.  The latter may result in surfaces for which a non-zero normal may not exist, and attempting to determine one when they do is of dubious value given the added expense.

I'll initiate a separate Pull Request for the changes to the GLSL shaders in the near future.  It can then serve as a reference while we figure out where else this needs to be addressed (HLSL, Mtl, etc.)

**Comment by jtran56** [comment]
Filed as internal issue #151439.

**Comment by davidgyu** [comment]
We believe this is now fixed by the three merged changes which address the GLSL, HLSL, and Metal shading language code paths. Thanks for the fixes, Barry!
