### ISSUE TITLE
opensubdiv errors out during the build

### ISSUE THREAD

**Issue by yzhao0227** [PixarAnimationStudios/OpenSubdiv#958]
Hi I am new to this linux build process. I am trying to build Opensubdiv in my Centos 7.4 by running travis_script_linux.sh script and it failed in the test: 3 - osd_regression (SEGFAULT) 4 - glImaging (SEGF. It looks like an OpenGL driver issue. But since I am new to this area and have no clue which way to get it It would be highly appreciates if anyone could tell me the solutions to solve the issues. 

++++++++++++++++++++++++++++++++++++++++++++++++++
Scanning dependencies of target doc
[100%] Built target doc
Test project /shots/media_database/download/OpenSubdiv/build
      Start  1: far_regression
 1/13 Test  #1: far_regression ...................   Passed   10.82 sec
      Start  2: far_perf
 2/13 Test  #2: far_perf .........................   Passed   10.84 sec
      Start  3: osd_regression
 3/13 Test  #3: osd_regression ...................***Exception: SegFault  0.08 sec
libGL: screen 0 does not appear to be DRI2 capable
libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
libGL: Can't open configuration file /home/yzhao/.drirc: No such file or directory.
libGL: Can't open configuration file /home/yzhao/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

      Start  4: glImaging
 4/13 Test  #4: glImaging ........................***Exception: SegFault  0.09 sec
libGL: screen 0 does not appear to be DRI2 capable
libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
libGL: Can't open configuration file /home/yzhao/.drirc: No such file or directory.
libGL: Can't open configuration file /home/yzhao/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
NVIDIA Corporation
Quadro K4000/PCIe/SSE2
1.4 (2.1.2 NVIDIA 340.102)
Init OpenGL -1.-1
GL error: PrintGLVersion 1280

      Start  5: far_tutorial_0
 5/13 Test  #5: far_tutorial_0 ...................   Passed    0.00 sec
      Start  6: far_tutorial_1
 6/13 Test  #6: far_tutorial_1 ...................   Passed    0.02 sec
      Start  7: far_tutorial_2
 7/13 Test  #7: far_tutorial_2 ...................   Passed    0.01 sec
      Start  8: far_tutorial_3
 8/13 Test  #8: far_tutorial_3 ...................   Passed    0.00 sec
      Start  9: far_tutorial_4
 9/13 Test  #9: far_tutorial_4 ...................   Passed    0.00 sec
      Start 10: far_tutorial_5
10/13 Test #10: far_tutorial_5 ...................   Passed    0.01 sec
      Start 11: far_tutorial_6
11/13 Test #11: far_tutorial_6 ...................   Passed    0.01 sec
      Start 12: far_tutorial_7
12/13 Test #12: far_tutorial_7 ...................   Passed    0.01 sec
      Start 13: far_tutorial_8
13/13 Test #13: far_tutorial_8 ...................   Passed    0.00 sec

85% tests passed, 2 tests failed out of 13

Total Test time (real) =  21.90 sec

The following tests FAILED:
          3 - osd_regression (SEGFAULT)
          4 - glImaging (SEGF

**Comment by jtran56** [comment]
Filed as internal issue #154321.

**Comment by davidgyu** [comment]
Marking closed. Please let us know if you are still having trouble running these tests.
