### ISSUE TITLE
Errors when building with CUDA 9

### ISSUE THREAD

**Issue by est77** [PixarAnimationStudios/OpenSubdiv#965]
[ 68%] Building NVCC (Device) object opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.o
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-architecture'

**Comment by davidgyu** [comment]
You can override the --gpu-architecture by specifying your own OSD_CUDA_NVCC_FLAGS during CMake configuration, e.g. -DOSD_CUDA_NVCC_FLAGS="--gpu-architecture compute_30" this will prevent the OpenSubdiv CMake configuration from trying to determine which compute architecture to target.

Ideally, OpenSubdiv would fully delegate this to the FindCUDA implementation, but that wasn't possible with some earlier versions of CMake.

**Comment by est77** [comment]
Yes, I saw OSD_CUDA_NVCC_FLAGS and managed to build after setting compute_30.

Thanks.

**Comment by est77** [comment]
Linux Centos 7, cmake 3.10.2, Cuda 9.0.

**Comment by davidgyu** [comment]
Thanks! It looks like FindCUDA in CMake 3.10.x supports selecting the compute model and we'll see what we can do to make use of that to have a better build default.

**Comment by est77** [comment]
Thanks!

**Comment by jtran56** [comment]
Filed as internal issue #159950.

**Comment by rlei-weta** [comment]
Hi @davidgyu

Did you guys have a chance to revisit build logic and use the newer FindCUDA, or the even more modern FindCUDAToolkit (CMake 3.17)?

**Comment by davidgyu** [comment]
Hey Richard,

Thanks for the heads up! We haven't had a chance to check that out yet.

**Comment by davidgyu** [comment]
We've implemented a simpler fix which sets the gpu architecture here only for older versions of CUDA while still allowing additional control using OSD_CUDA_NVCC_FLAGS when configuring CMake.
