### ISSUE TITLE
Build Error with dev branch Using VS2017 on Windows 10

### ISSUE THREAD

**Issue by adam-hartshorne** [PixarAnimationStudios/OpenSubdiv#967]
Using VS2017 (toolset v140 - in order for Cuda 9.1 compatibility) and using the latest version of Ptex, I get the following error in every example project which makes use of the Ptex library. I don't get this error when building with the main branch.

`error LNK2019: unresolved external symbol __std_reverse_trivially_swappable_4 referenced in function "void __cdecl std::_Buffered_inplace_merge_divide_and_conquer2<unsigned int *,struct Ptex::v2_2::PtexUtils::`anonymous namespace'::CompareRfaceIds>(unsigned int *,unsigned int *,unsigned int *,__int64,__int64,unsigned int * const,__int64,struct Ptex::v2_2::PtexUtils::`anonymous namespace'::CompareRfaceIds,unsigned int *,unsigned int *,__int64,__int64)" (??$_Buffered_inplace_merge_divide_and_conquer2@PEAIUCompareRfaceIds@?A0x9991d69d@PtexUtils@v2_2@Ptex@@@std@@YAXPEAI00_J1QEAI_JUCompareRfaceIds@?A0x9991d69d@PtexUtils@v2_2@Ptex@@0011@Z)`

**Comment by jtran56** [comment]
Filed as internal issue #161321.

**Comment by davidgyu** [comment]
We haven't seen this with local testing with VS2017, but we haven't tried all combinations of recent CUDA and Ptex releases. Are you seeing these errors with the v2.1 or v2.3 tags of the Ptex repo? Thanks!

**Comment by davidgyu** [comment]
Marking this closed. This is working correctly in our testing with VS2015 through VS2022.
Please reopen or file a new ticket with additional information if this is still a problem for you.
